#
# ======================================================================
# =====         FNT1001  v29      CDF incl jets @ 1800GeV     ==========
# ======================================================================
# 
fnt1001midp: fnt1001midp.cc cone-et-07.cc
	create-nlojet-user fnt1001midp.cc cone-et-07.cc  -o fnt1001midp -Wx,-O0,-Wall,-I${HOME}/include/lhpdf,-I../../common -Wl,-L${HOME}/lib/fastnlo,-llhpdf_cteq6,-lfastnloNlojet
