//
// File generated by /products/ROOT/4.00_06a/gcc-3.3/root/bin/rootcint at Fri Sep  9 03:35:34 2005.
// Do NOT change. Changes will be lost next time file is generated
//

#include "RConfig.h"
#if !defined(R__ACCESS_IN_SYMBOL)
//Break the privacy of classes -- Disabled for the moment
#define private public
#define protected public
#endif

#include "fastnloDict.h"
#include "TClass.h"
#include "TBuffer.h"
#include "TMemberInspector.h"
#include "TError.h"

#ifndef G__ROOT
#define G__ROOT
#endif

// Since CINT ignores the std namespace, we need to do so in this file.
namespace std {} using namespace std;

#include "RtypesImp.h"

#include "TVectorProxy.h"

namespace ROOT {
   namespace Shadow {
   } // Of namespace ROOT::Shadow
} // Of namespace ROOT

namespace ROOT {
   void TIncljets_ShowMembers(void *obj, TMemberInspector &R__insp, char *R__parent);
   static TClass *TIncljets_IsA(const void*);
   static void *new_TIncljets(void *p = 0);
   static void *newArray_TIncljets(Long_t size);
   static void delete_TIncljets(void *p);
   static void deleteArray_TIncljets(void *p);
   static void destruct_TIncljets(void *p);

   // Function generating the singleton type initializer
   TGenericClassInfo *GenerateInitInstance(const TIncljets*)
   {
      TIncljets *ptr = 0;
      static ROOT::TGenericClassInfo 
         instance("TIncljets", TIncljets::Class_Version(), "TIncljets.h", 24,
                  typeid(TIncljets), DefineBehavior(ptr, ptr),
                  &::TIncljets::Dictionary, &TIncljets_IsA, 0,
                  sizeof(TIncljets) );
      instance.SetNew(&new_TIncljets);
      instance.SetNewArray(&newArray_TIncljets);
      instance.SetDelete(&delete_TIncljets);
      instance.SetDeleteArray(&deleteArray_TIncljets);
      instance.SetDestructor(&destruct_TIncljets);
      return &instance;
   }
   // Static variable to force the class initialization
   static ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstance((const TIncljets*)0x0); R__UseDummy(_R__UNIQUE_(Init));
}

//______________________________________________________________________________
TClass *TIncljets::fgIsA = 0;  // static to hold class pointer

//______________________________________________________________________________
const char *TIncljets::Class_Name()
{
   return "TIncljets";
}

//______________________________________________________________________________
const char *TIncljets::ImplFileName()
{
   return ROOT::GenerateInitInstance((const TIncljets*)0x0)->GetImplFileName();
}

//______________________________________________________________________________
int TIncljets::ImplFileLine()
{
   return ROOT::GenerateInitInstance((const TIncljets*)0x0)->GetImplFileLine();
}

//______________________________________________________________________________
void TIncljets::Dictionary()
{
   fgIsA = ROOT::GenerateInitInstance((const TIncljets*)0x0)->GetClass();
}

//______________________________________________________________________________
TClass *TIncljets::Class()
{
   if (!fgIsA) fgIsA = ROOT::GenerateInitInstance((const TIncljets*)0x0)->GetClass();
   return fgIsA;
}

//______________________________________________________________________________
void TIncljets::Streamer(TBuffer &R__b)
{
   // Stream an object of class TIncljets.

   UInt_t R__s, R__c;
   if (R__b.IsReading()) {
      Version_t R__v = R__b.ReadVersion(&R__s, &R__c); if (R__v) { }
      TObject::Streamer(R__b);
      R__b >> nQ2;
      delete [] Q2high; 
      Q2high = new double[nQ2]; 
      R__b.ReadFastArray(Q2high,nQ2); 
      delete [] npt; 
      npt = new int[nQ2]; 
      R__b.ReadFastArray(npt,nQ2); 
      R__b >> nptmax;
      {
         vector<vector<double> > &R__stl =  pthigh;
         R__stl.clear();
         TClass *R__tcl1 = TBuffer::GetClass(typeid(vector<double,allocator<double> >));
         if (R__tcl1==0) {
            Error("pthigh streamer","Missing the TClass object for vector<double,allocator<double> >!");
            return;
         }
         int R__i, R__n;
         R__b >> R__n;
         R__stl.reserve(R__n);
         for (R__i = 0; R__i < R__n; R__i++) {
            vector<double,allocator<double> > R__t;
            R__b.StreamObject(&R__t,R__tcl1);
            R__stl.push_back(R__t);
         }
      }
      R__b >> ptlow;
      R__b >> nscalevar;
      {
         vector<double> &R__stl =  murscale;
         R__stl.clear();
         int R__i, R__n;
         R__b >> R__n;
         R__stl.reserve(R__n);
         for (R__i = 0; R__i < R__n; R__i++) {
            double R__t;
            R__b >> R__t;
            R__stl.push_back(R__t);
         }
      }
      {
         vector<vector<double> > &R__stl =  murval;
         R__stl.clear();
         TClass *R__tcl1 = TBuffer::GetClass(typeid(vector<double,allocator<double> >));
         if (R__tcl1==0) {
            Error("murval streamer","Missing the TClass object for vector<double,allocator<double> >!");
            return;
         }
         int R__i, R__n;
         R__b >> R__n;
         R__stl.reserve(R__n);
         for (R__i = 0; R__i < R__n; R__i++) {
            vector<double,allocator<double> > R__t;
            R__b.StreamObject(&R__t,R__tcl1);
            R__stl.push_back(R__t);
         }
      }
      {
         vector<double> &R__stl =  mufscale;
         R__stl.clear();
         int R__i, R__n;
         R__b >> R__n;
         R__stl.reserve(R__n);
         for (R__i = 0; R__i < R__n; R__i++) {
            double R__t;
            R__b >> R__t;
            R__stl.push_back(R__t);
         }
      }
      {
         vector<vector<double> > &R__stl =  mufval;
         R__stl.clear();
         TClass *R__tcl1 = TBuffer::GetClass(typeid(vector<double,allocator<double> >));
         if (R__tcl1==0) {
            Error("mufval streamer","Missing the TClass object for vector<double,allocator<double> >!");
            return;
         }
         int R__i, R__n;
         R__b >> R__n;
         R__stl.reserve(R__n);
         for (R__i = 0; R__i < R__n; R__i++) {
            vector<double,allocator<double> > R__t;
            R__b.StreamObject(&R__t,R__tcl1);
            R__stl.push_back(R__t);
         }
      }
      R__b >> ntot;
      {
         vector<vector<double> > &R__stl =  xlimit;
         R__stl.clear();
         TClass *R__tcl1 = TBuffer::GetClass(typeid(vector<double,allocator<double> >));
         if (R__tcl1==0) {
            Error("xlimit streamer","Missing the TClass object for vector<double,allocator<double> >!");
            return;
         }
         int R__i, R__n;
         R__b >> R__n;
         R__stl.reserve(R__n);
         for (R__i = 0; R__i < R__n; R__i++) {
            vector<double,allocator<double> > R__t;
            R__b.StreamObject(&R__t,R__tcl1);
            R__stl.push_back(R__t);
         }
      }
      R__b >> nsubproc;
      {
         vector<double> &R__stl =  nevents;
         R__stl.clear();
         int R__i, R__n;
         R__b >> R__n;
         R__stl.reserve(R__n);
         for (R__i = 0; R__i < R__n; R__i++) {
            double R__t;
            R__b >> R__t;
            R__stl.push_back(R__t);
         }
      }
      R__b >> nwrite;
      R__b >> ireaction;
      R__b >> s;
      R__b >> iproc;
      R__b >> ialgo;
      R__b >> JetResol1;
      R__b >> JetResol2;
      R__b >> npow;
      R__b >> npowmax;
      R__b >> Oalphas;
      R__b >> ixscheme;
      R__b >> ipdfwgt;
      {
         vector<vector<vector<double> > > &R__stl =  xsection;
         R__stl.clear();
         TClass *R__tcl1 = TBuffer::GetClass(typeid(vector<vector<double,allocator<double> >,allocator<vector<double,allocator<double> > > >));
         if (R__tcl1==0) {
            Error("xsection streamer","Missing the TClass object for vector<vector<double,allocator<double> >,allocator<vector<double,allocator<double> > > >!");
            return;
         }
         int R__i, R__n;
         R__b >> R__n;
         R__stl.reserve(R__n);
         for (R__i = 0; R__i < R__n; R__i++) {
            vector<vector<double,allocator<double> >,allocator<vector<double,allocator<double> > > > R__t;
            R__b.StreamObject(&R__t,R__tcl1);
            R__stl.push_back(R__t);
         }
      }
      R__b.ReadStaticArray((double*)q2binning);
      R__b.ReadStaticArray((double*)ptbinning);
      {
         vector<vector<vector<double> > > &R__stl =  rebinned;
         R__stl.clear();
         TClass *R__tcl1 = TBuffer::GetClass(typeid(vector<vector<double,allocator<double> >,allocator<vector<double,allocator<double> > > >));
         if (R__tcl1==0) {
            Error("rebinned streamer","Missing the TClass object for vector<vector<double,allocator<double> >,allocator<vector<double,allocator<double> > > >!");
            return;
         }
         int R__i, R__n;
         R__b >> R__n;
         R__stl.reserve(R__n);
         for (R__i = 0; R__i < R__n; R__i++) {
            vector<vector<double,allocator<double> >,allocator<vector<double,allocator<double> > > > R__t;
            R__b.StreamObject(&R__t,R__tcl1);
            R__stl.push_back(R__t);
         }
      }
      {
         vector<vector<vector<double> > > &R__stl =  reference;
         R__stl.clear();
         TClass *R__tcl1 = TBuffer::GetClass(typeid(vector<vector<double,allocator<double> >,allocator<vector<double,allocator<double> > > >));
         if (R__tcl1==0) {
            Error("reference streamer","Missing the TClass object for vector<vector<double,allocator<double> >,allocator<vector<double,allocator<double> > > >!");
            return;
         }
         int R__i, R__n;
         R__b >> R__n;
         R__stl.reserve(R__n);
         for (R__i = 0; R__i < R__n; R__i++) {
            vector<vector<double,allocator<double> >,allocator<vector<double,allocator<double> > > > R__t;
            R__b.StreamObject(&R__t,R__tcl1);
            R__stl.push_back(R__t);
         }
      }
      R__b >> lhapdf;
      R__b.CheckByteCount(R__s, R__c, TIncljets::IsA());
   } else {
      R__c = R__b.WriteVersion(TIncljets::IsA(), kTRUE);
      TObject::Streamer(R__b);
      R__b << nQ2;
      R__b.WriteFastArray(Q2high,nQ2); 
      R__b.WriteFastArray(npt,nQ2); 
      R__b << nptmax;
      {
         vector<vector<double> > &R__stl =  pthigh;
         int R__n=(&R__stl) ? int(R__stl.size()) : 0;
         R__b << R__n;
         if(R__n) {
         TClass *R__tcl1 = TBuffer::GetClass(typeid(vector<double,allocator<double> >));
         if (R__tcl1==0) {
            Error("pthigh streamer","Missing the TClass object for vector<double,allocator<double> >!");
            return;
         }
            vector<vector<double> >::iterator R__k;
            for (R__k = R__stl.begin(); R__k != R__stl.end(); ++R__k) {
            R__b.StreamObject((vector<double,allocator<double> >*)&(*R__k),R__tcl1);
            }
         }
      }
      R__b << ptlow;
      R__b << nscalevar;
      {
         vector<double> &R__stl =  murscale;
         int R__n=(&R__stl) ? int(R__stl.size()) : 0;
         R__b << R__n;
         if(R__n) {
            vector<double>::iterator R__k;
            for (R__k = R__stl.begin(); R__k != R__stl.end(); ++R__k) {
            R__b << (*R__k);
            }
         }
      }
      {
         vector<vector<double> > &R__stl =  murval;
         int R__n=(&R__stl) ? int(R__stl.size()) : 0;
         R__b << R__n;
         if(R__n) {
         TClass *R__tcl1 = TBuffer::GetClass(typeid(vector<double,allocator<double> >));
         if (R__tcl1==0) {
            Error("murval streamer","Missing the TClass object for vector<double,allocator<double> >!");
            return;
         }
            vector<vector<double> >::iterator R__k;
            for (R__k = R__stl.begin(); R__k != R__stl.end(); ++R__k) {
            R__b.StreamObject((vector<double,allocator<double> >*)&(*R__k),R__tcl1);
            }
         }
      }
      {
         vector<double> &R__stl =  mufscale;
         int R__n=(&R__stl) ? int(R__stl.size()) : 0;
         R__b << R__n;
         if(R__n) {
            vector<double>::iterator R__k;
            for (R__k = R__stl.begin(); R__k != R__stl.end(); ++R__k) {
            R__b << (*R__k);
            }
         }
      }
      {
         vector<vector<double> > &R__stl =  mufval;
         int R__n=(&R__stl) ? int(R__stl.size()) : 0;
         R__b << R__n;
         if(R__n) {
         TClass *R__tcl1 = TBuffer::GetClass(typeid(vector<double,allocator<double> >));
         if (R__tcl1==0) {
            Error("mufval streamer","Missing the TClass object for vector<double,allocator<double> >!");
            return;
         }
            vector<vector<double> >::iterator R__k;
            for (R__k = R__stl.begin(); R__k != R__stl.end(); ++R__k) {
            R__b.StreamObject((vector<double,allocator<double> >*)&(*R__k),R__tcl1);
            }
         }
      }
      R__b << ntot;
      {
         vector<vector<double> > &R__stl =  xlimit;
         int R__n=(&R__stl) ? int(R__stl.size()) : 0;
         R__b << R__n;
         if(R__n) {
         TClass *R__tcl1 = TBuffer::GetClass(typeid(vector<double,allocator<double> >));
         if (R__tcl1==0) {
            Error("xlimit streamer","Missing the TClass object for vector<double,allocator<double> >!");
            return;
         }
            vector<vector<double> >::iterator R__k;
            for (R__k = R__stl.begin(); R__k != R__stl.end(); ++R__k) {
            R__b.StreamObject((vector<double,allocator<double> >*)&(*R__k),R__tcl1);
            }
         }
      }
      R__b << nsubproc;
      {
         vector<double> &R__stl =  nevents;
         int R__n=(&R__stl) ? int(R__stl.size()) : 0;
         R__b << R__n;
         if(R__n) {
            vector<double>::iterator R__k;
            for (R__k = R__stl.begin(); R__k != R__stl.end(); ++R__k) {
            R__b << (*R__k);
            }
         }
      }
      R__b << nwrite;
      R__b << ireaction;
      R__b << s;
      R__b << iproc;
      R__b << ialgo;
      R__b << JetResol1;
      R__b << JetResol2;
      R__b << npow;
      R__b << npowmax;
      R__b << Oalphas;
      R__b << ixscheme;
      R__b << ipdfwgt;
      {
         vector<vector<vector<double> > > &R__stl =  xsection;
         int R__n=(&R__stl) ? int(R__stl.size()) : 0;
         R__b << R__n;
         if(R__n) {
         TClass *R__tcl1 = TBuffer::GetClass(typeid(vector<vector<double,allocator<double> >,allocator<vector<double,allocator<double> > > >));
         if (R__tcl1==0) {
            Error("xsection streamer","Missing the TClass object for vector<vector<double,allocator<double> >,allocator<vector<double,allocator<double> > > >!");
            return;
         }
            vector<vector<vector<double> > >::iterator R__k;
            for (R__k = R__stl.begin(); R__k != R__stl.end(); ++R__k) {
            R__b.StreamObject((vector<vector<double,allocator<double> >,allocator<vector<double,allocator<double> > > >*)&(*R__k),R__tcl1);
            }
         }
      }
      R__b.WriteArray(q2binning, 5);
      R__b.WriteArray(ptbinning, 5);
      {
         vector<vector<vector<double> > > &R__stl =  rebinned;
         int R__n=(&R__stl) ? int(R__stl.size()) : 0;
         R__b << R__n;
         if(R__n) {
         TClass *R__tcl1 = TBuffer::GetClass(typeid(vector<vector<double,allocator<double> >,allocator<vector<double,allocator<double> > > >));
         if (R__tcl1==0) {
            Error("rebinned streamer","Missing the TClass object for vector<vector<double,allocator<double> >,allocator<vector<double,allocator<double> > > >!");
            return;
         }
            vector<vector<vector<double> > >::iterator R__k;
            for (R__k = R__stl.begin(); R__k != R__stl.end(); ++R__k) {
            R__b.StreamObject((vector<vector<double,allocator<double> >,allocator<vector<double,allocator<double> > > >*)&(*R__k),R__tcl1);
            }
         }
      }
      {
         vector<vector<vector<double> > > &R__stl =  reference;
         int R__n=(&R__stl) ? int(R__stl.size()) : 0;
         R__b << R__n;
         if(R__n) {
         TClass *R__tcl1 = TBuffer::GetClass(typeid(vector<vector<double,allocator<double> >,allocator<vector<double,allocator<double> > > >));
         if (R__tcl1==0) {
            Error("reference streamer","Missing the TClass object for vector<vector<double,allocator<double> >,allocator<vector<double,allocator<double> > > >!");
            return;
         }
            vector<vector<vector<double> > >::iterator R__k;
            for (R__k = R__stl.begin(); R__k != R__stl.end(); ++R__k) {
            R__b.StreamObject((vector<vector<double,allocator<double> >,allocator<vector<double,allocator<double> > > >*)&(*R__k),R__tcl1);
            }
         }
      }
      R__b << lhapdf;
      R__b.SetByteCount(R__c, kTRUE);
   }
}

//______________________________________________________________________________
void TIncljets::ShowMembers(TMemberInspector &R__insp, char *R__parent)
{
      // Inspect the data members of an object of class TIncljets.

      TClass *R__cl = TIncljets::IsA();
      Int_t R__ncp = strlen(R__parent);
      if (R__ncp || R__cl || R__insp.IsA()) { }
      R__insp.Inspect(R__cl, R__parent, "nQ2", &nQ2);
      R__insp.Inspect(R__cl, R__parent, "*Q2high", &Q2high);
      R__insp.Inspect(R__cl, R__parent, "*npt", &npt);
      R__insp.Inspect(R__cl, R__parent, "nptmax", &nptmax);
      R__insp.Inspect(R__cl, R__parent, "pthigh", (void*)&pthigh);
      ROOT::GenericShowMembers("vector<vector<double> >", (void*)&pthigh, R__insp, strcat(R__parent,"pthigh."),false);
      R__parent[R__ncp] = 0;
      R__insp.Inspect(R__cl, R__parent, "ptlow", &ptlow);
      R__insp.Inspect(R__cl, R__parent, "nscalevar", &nscalevar);
      R__insp.Inspect(R__cl, R__parent, "murscale", (void*)&murscale);
      ROOT::GenericShowMembers("vector<double>", (void*)&murscale, R__insp, strcat(R__parent,"murscale."),false);
      R__parent[R__ncp] = 0;
      R__insp.Inspect(R__cl, R__parent, "murval", (void*)&murval);
      ROOT::GenericShowMembers("vector<vector<double> >", (void*)&murval, R__insp, strcat(R__parent,"murval."),false);
      R__parent[R__ncp] = 0;
      R__insp.Inspect(R__cl, R__parent, "mufscale", (void*)&mufscale);
      ROOT::GenericShowMembers("vector<double>", (void*)&mufscale, R__insp, strcat(R__parent,"mufscale."),false);
      R__parent[R__ncp] = 0;
      R__insp.Inspect(R__cl, R__parent, "mufval", (void*)&mufval);
      ROOT::GenericShowMembers("vector<vector<double> >", (void*)&mufval, R__insp, strcat(R__parent,"mufval."),false);
      R__parent[R__ncp] = 0;
      R__insp.Inspect(R__cl, R__parent, "ntot", &ntot);
      R__insp.Inspect(R__cl, R__parent, "xlimit", (void*)&xlimit);
      ROOT::GenericShowMembers("vector<vector<double> >", (void*)&xlimit, R__insp, strcat(R__parent,"xlimit."),false);
      R__parent[R__ncp] = 0;
      R__insp.Inspect(R__cl, R__parent, "disweights", (void*)&disweights);
      ROOT::GenericShowMembers("vector<vector<vector<vector<weight_dis> > > >", (void*)&disweights, R__insp, strcat(R__parent,"disweights."),true);
      R__parent[R__ncp] = 0;
      R__insp.Inspect(R__cl, R__parent, "pdf", (void*)&pdf);
      ROOT::GenericShowMembers("vector<vector<vector<weight_dis> > >", (void*)&pdf, R__insp, strcat(R__parent,"pdf."),true);
      R__parent[R__ncp] = 0;
      R__insp.Inspect(R__cl, R__parent, "nsubproc", &nsubproc);
      R__insp.Inspect(R__cl, R__parent, "nevents", (void*)&nevents);
      ROOT::GenericShowMembers("vector<double>", (void*)&nevents, R__insp, strcat(R__parent,"nevents."),false);
      R__parent[R__ncp] = 0;
      R__insp.Inspect(R__cl, R__parent, "nwrite", &nwrite);
      R__insp.Inspect(R__cl, R__parent, "ireaction", &ireaction);
      R__insp.Inspect(R__cl, R__parent, "s", &s);
      R__insp.Inspect(R__cl, R__parent, "iproc", &iproc);
      R__insp.Inspect(R__cl, R__parent, "ialgo", &ialgo);
      R__insp.Inspect(R__cl, R__parent, "JetResol1", &JetResol1);
      R__insp.Inspect(R__cl, R__parent, "JetResol2", &JetResol2);
      R__insp.Inspect(R__cl, R__parent, "npow", &npow);
      R__insp.Inspect(R__cl, R__parent, "npowmax", &npowmax);
      R__insp.Inspect(R__cl, R__parent, "Oalphas", &Oalphas);
      R__insp.Inspect(R__cl, R__parent, "ixscheme", &ixscheme);
      R__insp.Inspect(R__cl, R__parent, "ipdfwgt", &ipdfwgt);
      R__insp.Inspect(R__cl, R__parent, "xsection", (void*)&xsection);
      ROOT::GenericShowMembers("vector<vector<vector<double> > >", (void*)&xsection, R__insp, strcat(R__parent,"xsection."),false);
      R__parent[R__ncp] = 0;
      R__insp.Inspect(R__cl, R__parent, "q2binning[5]", q2binning);
      R__insp.Inspect(R__cl, R__parent, "ptbinning[5]", ptbinning);
      R__insp.Inspect(R__cl, R__parent, "rebinned", (void*)&rebinned);
      ROOT::GenericShowMembers("vector<vector<vector<double> > >", (void*)&rebinned, R__insp, strcat(R__parent,"rebinned."),false);
      R__parent[R__ncp] = 0;
      R__insp.Inspect(R__cl, R__parent, "reference", (void*)&reference);
      ROOT::GenericShowMembers("vector<vector<vector<double> > >", (void*)&reference, R__insp, strcat(R__parent,"reference."),false);
      R__parent[R__ncp] = 0;
      R__insp.Inspect(R__cl, R__parent, "*lhapdf", &lhapdf);
      TObject::ShowMembers(R__insp, R__parent);
}

namespace ROOT {
   // Return the actual TClass for the object argument
   static TClass *TIncljets_IsA(const void *obj) {
      return ((::TIncljets*)obj)->IsA();
   }
   // Wrappers around operator new
   static void *new_TIncljets(void *p) {
      return  p ? new(p) ::TIncljets : new ::TIncljets;
   }
   static void *newArray_TIncljets(Long_t size) {
      return new ::TIncljets[size];
   }
   // Wrapper around operator delete
   static void delete_TIncljets(void *p) {
      delete ((::TIncljets*)p);
   }
   static void deleteArray_TIncljets(void *p) {
      delete [] ((::TIncljets*)p);
   }
   static void destruct_TIncljets(void *p) {
      typedef ::TIncljets current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOT for class ::TIncljets

//________________________________________________________________________________________________________________________
namespace ROOT {
   typedef vector<double> vectorlEdoublegR;
   static void stl_streamer_vectorlEdoublegR(TBuffer &R__b, void *R__p)
   {
      if (gDebug>1) Info(__FILE__,"Running compiled streamer for vector<double> at %p",R__p);
      vector<double> &R__stl = *(vector<double> *)R__p;
      if (R__b.IsReading()) {
         R__stl.clear();
         int R__i, R__n;
         R__b >> R__n;
         R__stl.reserve(R__n);
         for (R__i = 0; R__i < R__n; R__i++) {
            double R__t;
            R__b >> R__t;
            R__stl.push_back(R__t);
         }
      } else {
         int R__n=(&R__stl) ? int(R__stl.size()) : 0;
         R__b << R__n;
         if(R__n) {
            vector<double>::iterator R__k;
            for (R__k = R__stl.begin(); R__k != R__stl.end(); ++R__k) {
            R__b << (*R__k);
            }
         }
      }
   } // end of vector<double,allocator<double> > streamer
} // close namespace ROOT

// Register the streamer (a typedef is used to avoid problem with macro parameters
RootStlStreamer(vectorlEdoublegR,stl_streamer_vectorlEdoublegR);

//________________________________________________________________________________________________________________________
namespace ROOT {
   typedef vector<vector<double> > vectorlEvectorlEdoublegRsPgR;
   static void stl_streamer_vectorlEvectorlEdoublegRsPgR(TBuffer &R__b, void *R__p)
   {
      if (gDebug>1) Info(__FILE__,"Running compiled streamer for vector<vector<double> > at %p",R__p);
      vector<vector<double> > &R__stl = *(vector<vector<double> > *)R__p;
      if (R__b.IsReading()) {
         R__stl.clear();
         TClass *R__tcl1 = TBuffer::GetClass(typeid(vector<double>));
         int R__i, R__n;
         R__b >> R__n;
         R__stl.reserve(R__n);
         for (R__i = 0; R__i < R__n; R__i++) {
            vector<double> R__t;
            R__b.StreamObject(&R__t,R__tcl1);
            R__stl.push_back(R__t);
         }
      } else {
         int R__n=(&R__stl) ? int(R__stl.size()) : 0;
         R__b << R__n;
         if(R__n) {
            TClass *R__tcl1 = TBuffer::GetClass(typeid(vector<double>));
            if (R__tcl1==0) {
               Error("vector<vector<double> > streamer","Missing the TClass object for vector<double>!");
               return;
            }
            vector<vector<double> >::iterator R__k;
            for (R__k = R__stl.begin(); R__k != R__stl.end(); ++R__k) {
            R__b.StreamObject((vector<double>*)&(*R__k),R__tcl1);
            }
         }
      }
   } // end of vector<vector<double,allocator<double> >,allocator<vector<double,allocator<double> > > > streamer
} // close namespace ROOT

// Register the streamer (a typedef is used to avoid problem with macro parameters
RootStlStreamer(vectorlEvectorlEdoublegRsPgR,stl_streamer_vectorlEvectorlEdoublegRsPgR);

//________________________________________________________________________________________________________________________
namespace ROOT {
   typedef vector<vector<vector<double> > > vectorlEvectorlEvectorlEdoublegRsPgRsPgR;
   static void stl_streamer_vectorlEvectorlEvectorlEdoublegRsPgRsPgR(TBuffer &R__b, void *R__p)
   {
      if (gDebug>1) Info(__FILE__,"Running compiled streamer for vector<vector<vector<double> > > at %p",R__p);
      vector<vector<vector<double> > > &R__stl = *(vector<vector<vector<double> > > *)R__p;
      if (R__b.IsReading()) {
         R__stl.clear();
         TClass *R__tcl1 = TBuffer::GetClass(typeid(vector<vector<double> >));
         int R__i, R__n;
         R__b >> R__n;
         R__stl.reserve(R__n);
         for (R__i = 0; R__i < R__n; R__i++) {
            vector<vector<double> > R__t;
            R__b.StreamObject(&R__t,R__tcl1);
            R__stl.push_back(R__t);
         }
      } else {
         int R__n=(&R__stl) ? int(R__stl.size()) : 0;
         R__b << R__n;
         if(R__n) {
            TClass *R__tcl1 = TBuffer::GetClass(typeid(vector<vector<double> >));
            if (R__tcl1==0) {
               Error("vector<vector<vector<double> > > streamer","Missing the TClass object for vector<vector<double> >!");
               return;
            }
            vector<vector<vector<double> > >::iterator R__k;
            for (R__k = R__stl.begin(); R__k != R__stl.end(); ++R__k) {
            R__b.StreamObject((vector<vector<double> >*)&(*R__k),R__tcl1);
            }
         }
      }
   } // end of vector<vector<vector<double,allocator<double> >,allocator<vector<double,allocator<double> > > >,allocator<vector<vector<double,allocator<double> >,allocator<vector<double,allocator<double> > > > > > streamer
} // close namespace ROOT

// Register the streamer (a typedef is used to avoid problem with macro parameters
RootStlStreamer(vectorlEvectorlEvectorlEdoublegRsPgRsPgR,stl_streamer_vectorlEvectorlEvectorlEdoublegRsPgRsPgR);

namespace ROOT {
   void vectorlEdoublegR_ShowMembers(void *obj, TMemberInspector &R__insp, char *R__parent);
   static void vectorlEdoublegR_Dictionary();
   static TClass *vectorlEdoublegR_IsA(const void*);
   static void *new_vectorlEdoublegR(void *p = 0);
   static void *newArray_vectorlEdoublegR(Long_t size);
   static void delete_vectorlEdoublegR(void *p);
   static void deleteArray_vectorlEdoublegR(void *p);
   static void destruct_vectorlEdoublegR(void *p);

   // Function generating the singleton type initializer
   static // The GenerateInitInstance for STL are not unique and should not be externally accessible
   TGenericClassInfo *GenerateInitInstance(const vector<double>*)
   {
      vector<double> *ptr = 0;
      static ROOT::TGenericClassInfo 
         instance("vector<double>", GetROOT()->GetVersionInt() / 100, "prec_stl/vector", 42,
                  typeid(vector<double>), DefineBehavior(ptr, ptr),
                  0, &vectorlEdoublegR_Dictionary, &vectorlEdoublegR_IsA, 0,
                  sizeof(vector<double>) );
      instance.SetNew(&new_vectorlEdoublegR);
      instance.SetNewArray(&newArray_vectorlEdoublegR);
      instance.SetDelete(&delete_vectorlEdoublegR);
      instance.SetDeleteArray(&deleteArray_vectorlEdoublegR);
      instance.SetDestructor(&destruct_vectorlEdoublegR);
      instance.AdoptCollectionProxy(new ROOT::TVectorProxy<vector<double> >);
      return &instance;
   }
   // Static variable to force the class initialization
   static ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstance((const vector<double>*)0x0); R__UseDummy(_R__UNIQUE_(Init));

   // Dictionary for non-ClassDef classes
   static void vectorlEdoublegR_Dictionary() {
      ROOT::GenerateInitInstance((const vector<double>*)0x0)->GetClass();
   }

}

namespace ROOT {
   // Return the actual TClass for the object argument
   static TClass *vectorlEdoublegR_IsA(const void *obj) {
      return GetROOT()->GetClass(typeid(*(vector<double>*)obj));
   }
   // Wrappers around operator new
   static void *new_vectorlEdoublegR(void *p) {
      return  p ? ::new((ROOT::TOperatorNewHelper*)p) vector<double> : new vector<double>;
   }
   static void *newArray_vectorlEdoublegR(Long_t size) {
      return new vector<double>[size];
   }
   // Wrapper around operator delete
   static void delete_vectorlEdoublegR(void *p) {
      delete ((vector<double>*)p);
   }
   static void deleteArray_vectorlEdoublegR(void *p) {
      delete [] ((vector<double>*)p);
   }
   static void destruct_vectorlEdoublegR(void *p) {
      typedef vector<double> current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOT for class vector<double>

namespace ROOT {
   void vectorlEvectorlEdoublegRsPgR_ShowMembers(void *obj, TMemberInspector &R__insp, char *R__parent);
   static void vectorlEvectorlEdoublegRsPgR_Dictionary();
   static TClass *vectorlEvectorlEdoublegRsPgR_IsA(const void*);
   static void *new_vectorlEvectorlEdoublegRsPgR(void *p = 0);
   static void *newArray_vectorlEvectorlEdoublegRsPgR(Long_t size);
   static void delete_vectorlEvectorlEdoublegRsPgR(void *p);
   static void deleteArray_vectorlEvectorlEdoublegRsPgR(void *p);
   static void destruct_vectorlEvectorlEdoublegRsPgR(void *p);

   // Function generating the singleton type initializer
   static // The GenerateInitInstance for STL are not unique and should not be externally accessible
   TGenericClassInfo *GenerateInitInstance(const vector<vector<double> >*)
   {
      vector<vector<double> > *ptr = 0;
      static ROOT::TGenericClassInfo 
         instance("vector<vector<double> >", GetROOT()->GetVersionInt() / 100, "prec_stl/vector", 42,
                  typeid(vector<vector<double> >), DefineBehavior(ptr, ptr),
                  0, &vectorlEvectorlEdoublegRsPgR_Dictionary, &vectorlEvectorlEdoublegRsPgR_IsA, 0,
                  sizeof(vector<vector<double> >) );
      instance.SetNew(&new_vectorlEvectorlEdoublegRsPgR);
      instance.SetNewArray(&newArray_vectorlEvectorlEdoublegRsPgR);
      instance.SetDelete(&delete_vectorlEvectorlEdoublegRsPgR);
      instance.SetDeleteArray(&deleteArray_vectorlEvectorlEdoublegRsPgR);
      instance.SetDestructor(&destruct_vectorlEvectorlEdoublegRsPgR);
      instance.AdoptCollectionProxy(new ROOT::TVectorProxy<vector<vector<double> > >);
      return &instance;
   }
   // Static variable to force the class initialization
   static ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstance((const vector<vector<double> >*)0x0); R__UseDummy(_R__UNIQUE_(Init));

   // Dictionary for non-ClassDef classes
   static void vectorlEvectorlEdoublegRsPgR_Dictionary() {
      ROOT::GenerateInitInstance((const vector<vector<double> >*)0x0)->GetClass();
   }

}

namespace ROOT {
   // Return the actual TClass for the object argument
   static TClass *vectorlEvectorlEdoublegRsPgR_IsA(const void *obj) {
      return GetROOT()->GetClass(typeid(*(vector<vector<double> >*)obj));
   }
   // Wrappers around operator new
   static void *new_vectorlEvectorlEdoublegRsPgR(void *p) {
      return  p ? ::new((ROOT::TOperatorNewHelper*)p) vector<vector<double> > : new vector<vector<double> >;
   }
   static void *newArray_vectorlEvectorlEdoublegRsPgR(Long_t size) {
      return new vector<vector<double> >[size];
   }
   // Wrapper around operator delete
   static void delete_vectorlEvectorlEdoublegRsPgR(void *p) {
      delete ((vector<vector<double> >*)p);
   }
   static void deleteArray_vectorlEvectorlEdoublegRsPgR(void *p) {
      delete [] ((vector<vector<double> >*)p);
   }
   static void destruct_vectorlEvectorlEdoublegRsPgR(void *p) {
      typedef vector<vector<double> > current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOT for class vector<vector<double> >

namespace ROOT {
   void vectorlEvectorlEvectorlEdoublegRsPgRsPgR_ShowMembers(void *obj, TMemberInspector &R__insp, char *R__parent);
   static void vectorlEvectorlEvectorlEdoublegRsPgRsPgR_Dictionary();
   static TClass *vectorlEvectorlEvectorlEdoublegRsPgRsPgR_IsA(const void*);
   static void *new_vectorlEvectorlEvectorlEdoublegRsPgRsPgR(void *p = 0);
   static void *newArray_vectorlEvectorlEvectorlEdoublegRsPgRsPgR(Long_t size);
   static void delete_vectorlEvectorlEvectorlEdoublegRsPgRsPgR(void *p);
   static void deleteArray_vectorlEvectorlEvectorlEdoublegRsPgRsPgR(void *p);
   static void destruct_vectorlEvectorlEvectorlEdoublegRsPgRsPgR(void *p);

   // Function generating the singleton type initializer
   static // The GenerateInitInstance for STL are not unique and should not be externally accessible
   TGenericClassInfo *GenerateInitInstance(const vector<vector<vector<double> > >*)
   {
      vector<vector<vector<double> > > *ptr = 0;
      static ROOT::TGenericClassInfo 
         instance("vector<vector<vector<double> > >", GetROOT()->GetVersionInt() / 100, "prec_stl/vector", 42,
                  typeid(vector<vector<vector<double> > >), DefineBehavior(ptr, ptr),
                  0, &vectorlEvectorlEvectorlEdoublegRsPgRsPgR_Dictionary, &vectorlEvectorlEvectorlEdoublegRsPgRsPgR_IsA, 0,
                  sizeof(vector<vector<vector<double> > >) );
      instance.SetNew(&new_vectorlEvectorlEvectorlEdoublegRsPgRsPgR);
      instance.SetNewArray(&newArray_vectorlEvectorlEvectorlEdoublegRsPgRsPgR);
      instance.SetDelete(&delete_vectorlEvectorlEvectorlEdoublegRsPgRsPgR);
      instance.SetDeleteArray(&deleteArray_vectorlEvectorlEvectorlEdoublegRsPgRsPgR);
      instance.SetDestructor(&destruct_vectorlEvectorlEvectorlEdoublegRsPgRsPgR);
      instance.AdoptCollectionProxy(new ROOT::TVectorProxy<vector<vector<vector<double> > > >);
      return &instance;
   }
   // Static variable to force the class initialization
   static ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstance((const vector<vector<vector<double> > >*)0x0); R__UseDummy(_R__UNIQUE_(Init));

   // Dictionary for non-ClassDef classes
   static void vectorlEvectorlEvectorlEdoublegRsPgRsPgR_Dictionary() {
      ROOT::GenerateInitInstance((const vector<vector<vector<double> > >*)0x0)->GetClass();
   }

}

namespace ROOT {
   // Return the actual TClass for the object argument
   static TClass *vectorlEvectorlEvectorlEdoublegRsPgRsPgR_IsA(const void *obj) {
      return GetROOT()->GetClass(typeid(*(vector<vector<vector<double> > >*)obj));
   }
   // Wrappers around operator new
   static void *new_vectorlEvectorlEvectorlEdoublegRsPgRsPgR(void *p) {
      return  p ? ::new((ROOT::TOperatorNewHelper*)p) vector<vector<vector<double> > > : new vector<vector<vector<double> > >;
   }
   static void *newArray_vectorlEvectorlEvectorlEdoublegRsPgRsPgR(Long_t size) {
      return new vector<vector<vector<double> > >[size];
   }
   // Wrapper around operator delete
   static void delete_vectorlEvectorlEvectorlEdoublegRsPgRsPgR(void *p) {
      delete ((vector<vector<vector<double> > >*)p);
   }
   static void deleteArray_vectorlEvectorlEvectorlEdoublegRsPgRsPgR(void *p) {
      delete [] ((vector<vector<vector<double> > >*)p);
   }
   static void destruct_vectorlEvectorlEvectorlEdoublegRsPgRsPgR(void *p) {
      typedef vector<vector<vector<double> > > current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOT for class vector<vector<vector<double> > >

/********************************************************
* fastnloDict.C
********************************************************/

#ifdef G__MEMTEST
#undef malloc
#undef free
#endif

extern "C" void G__cpp_reset_tagtablefastnloDict();

extern "C" void G__set_cpp_environmentfastnloDict() {
  G__add_compiledheader("TROOT.h");
  G__add_compiledheader("TMemberInspector.h");
  G__add_compiledheader("TIncljets.h");
  G__cpp_reset_tagtablefastnloDict();
}
class G__fastnloDictdOC_tag {};

void* operator new(size_t size,G__fastnloDictdOC_tag* p) {
  if(p && G__PVOID!=G__getgvp()) return((void*)p);
#ifndef G__ROOT
  return(malloc(size));
#else
  return(::operator new(size));
#endif
}

/* dummy, for exception */
#ifdef G__EH_DUMMY_DELETE
void operator delete(void *p,G__fastnloDictdOC_tag* x) {
  if((long)p==G__getgvp() && G__PVOID!=G__getgvp()) return;
#ifndef G__ROOT
  free(p);
#else
  ::operator delete(p);
#endif
}
#endif

static void G__operator_delete(void *p) {
  if((long)p==G__getgvp() && G__PVOID!=G__getgvp()) return;
#ifndef G__ROOT
  free(p);
#else
  ::operator delete(p);
#endif
}

void G__DELDMY_fastnloDictdOC() { G__operator_delete(0); }

extern "C" int G__cpp_dllrevfastnloDict() { return(30051515); }

/*********************************************************
* Member function Interface Method
*********************************************************/

/* TIncljets */
static int G__fastnloDict_137_1_0(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
   TIncljets *p=NULL;
   if(G__getaryconstruct()) p=new TIncljets[G__getaryconstruct()];
   else                    p=new TIncljets;
      result7->obj.i = (long)p;
      result7->ref = (long)p;
      result7->type = 'u';
      result7->tagnum = G__get_linked_tagnum(&G__fastnloDictLN_TIncljets);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__fastnloDict_137_2_0(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__letdouble(result7,100,(double)((TIncljets*)(G__getstructoffset()))->alphas((double)G__double(libp->para[0]),(double)G__double(libp->para[1])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__fastnloDict_137_3_0(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__setnull(result7);
      ((TIncljets*)(G__getstructoffset()))->ReadTable(*((string*)G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__fastnloDict_137_4_0(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__setnull(result7);
      ((TIncljets*)(G__getstructoffset()))->ReadPDF(*((string*)G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__fastnloDict_137_5_0(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__setnull(result7);
      ((TIncljets*)(G__getstructoffset()))->SetPDFSet((int)G__int(libp->para[0]));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__fastnloDict_137_6_0(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__setnull(result7);
      ((TIncljets*)(G__getstructoffset()))->FillPDFCache((double)G__double(libp->para[0]));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__fastnloDict_137_7_0(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__setnull(result7);
      ((TIncljets*)(G__getstructoffset()))->ResetXsection();
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__fastnloDict_137_8_0(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
   switch(libp->paran) {
   case 2:
      G__setnull(result7);
      ((TIncljets*)(G__getstructoffset()))->CalcXsection((double)G__double(libp->para[0]),(int)G__int(libp->para[1]));
      break;
   case 1:
      G__setnull(result7);
      ((TIncljets*)(G__getstructoffset()))->CalcXsection((double)G__double(libp->para[0]));
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__fastnloDict_137_9_0(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__letdouble(result7,100,(double)((TIncljets*)(G__getstructoffset()))->GetXsection((int)G__int(libp->para[0]),(int)G__int(libp->para[1])
,(int)G__int(libp->para[2])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__fastnloDict_137_0_1(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__setnull(result7);
      ((TIncljets*)(G__getstructoffset()))->Rebin();
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__fastnloDict_137_1_1(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__letdouble(result7,100,(double)((TIncljets*)(G__getstructoffset()))->GetRebinned((int)G__int(libp->para[0]),(int)G__int(libp->para[1])
,(int)G__int(libp->para[2])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__fastnloDict_137_2_1(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__setnull(result7);
      ((TIncljets*)(G__getstructoffset()))->ResetReference();
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__fastnloDict_137_3_1(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__setnull(result7);
      ((TIncljets*)(G__getstructoffset()))->ReadReference(*((string*)G__int(libp->para[0])),(int)G__int(libp->para[1]));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__fastnloDict_137_4_1(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__letdouble(result7,100,(double)((TIncljets*)(G__getstructoffset()))->GetReference((int)G__int(libp->para[0]),(int)G__int(libp->para[1])
,(int)G__int(libp->para[2])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__fastnloDict_137_5_1(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
   G__letint(result7,85,(long)TIncljets::Class());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__fastnloDict_137_6_1(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
   G__letint(result7,67,(long)TIncljets::Class_Name());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__fastnloDict_137_7_1(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__letint(result7,115,(long)TIncljets::Class_Version());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__fastnloDict_137_8_1(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__setnull(result7);
      TIncljets::Dictionary();
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__fastnloDict_137_9_1(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
   G__letint(result7,85,(long)((const TIncljets*)(G__getstructoffset()))->IsA());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__fastnloDict_137_0_2(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__setnull(result7);
      ((TIncljets*)(G__getstructoffset()))->ShowMembers(*(TMemberInspector*)libp->para[0].ref,(char*)G__int(libp->para[1]));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__fastnloDict_137_1_2(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__setnull(result7);
      ((TIncljets*)(G__getstructoffset()))->Streamer(*(TBuffer*)libp->para[0].ref);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__fastnloDict_137_2_2(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__setnull(result7);
      ((TIncljets*)(G__getstructoffset()))->StreamerNVirtual(*(TBuffer*)libp->para[0].ref);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__fastnloDict_137_3_2(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
   G__letint(result7,67,(long)TIncljets::DeclFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__fastnloDict_137_4_2(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__letint(result7,105,(long)TIncljets::ImplFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__fastnloDict_137_5_2(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
   G__letint(result7,67,(long)TIncljets::ImplFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__fastnloDict_137_6_2(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__letint(result7,105,(long)TIncljets::DeclFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic copy constructor
static int G__fastnloDict_137_7_2(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash)
{
   TIncljets *p;
   void *xtmp = (void*)G__int(libp->para[0]);
   p=new TIncljets(*(TIncljets*)xtmp);
   result7->obj.i = (long)p;
   result7->ref = (long)p;
   result7->type = 'u';
   result7->tagnum = G__get_linked_tagnum(&G__fastnloDictLN_TIncljets);
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef TIncljets G__TTIncljets;
static int G__fastnloDict_137_8_2(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
   if(0==G__getstructoffset()) return(1);
   if(G__getaryconstruct())
     if(G__PVOID==G__getgvp())
       delete[] (TIncljets *)(G__getstructoffset());
     else
       for(int i=G__getaryconstruct()-1;i>=0;i--)
         delete (TIncljets *)((G__getstructoffset())+sizeof(TIncljets)*i);
   else  delete (TIncljets *)(G__getstructoffset());
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic assignment operator
static int G__fastnloDict_137_9_2(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
   TIncljets *dest = (TIncljets*)(G__getstructoffset());
   *dest = (*(TIncljets*)libp->para[0].ref);
   const TIncljets& obj = *dest;
   result7->ref=(long)(&obj); result7->obj.i=(long)(&obj);
   return(1 || funcname || hash || result7 || libp) ;
}


/* Setting up global function */

/*********************************************************
* Member function Stub
*********************************************************/

/* TIncljets */

/*********************************************************
* Global function Stub
*********************************************************/

/*********************************************************
* Get size of pointer to member function
*********************************************************/
class G__Sizep2memfuncfastnloDict {
 public:
  G__Sizep2memfuncfastnloDict() {p=&G__Sizep2memfuncfastnloDict::sizep2memfunc;}
    size_t sizep2memfunc() { return(sizeof(p)); }
  private:
    size_t (G__Sizep2memfuncfastnloDict::*p)();
};

size_t G__get_sizep2memfuncfastnloDict()
{
  G__Sizep2memfuncfastnloDict a;
  G__setsizep2memfunc((int)a.sizep2memfunc());
  return((size_t)a.sizep2memfunc());
}


/*********************************************************
* virtual base class offset calculation interface
*********************************************************/

   /* Setting up class inheritance */

/*********************************************************
* Inheritance information setup/
*********************************************************/
extern "C" void G__cpp_setup_inheritancefastnloDict() {

   /* Setting up class inheritance */
   if(0==G__getnumbaseclass(G__get_linked_tagnum(&G__fastnloDictLN_TIncljets))) {
     TIncljets *G__Lderived;
     G__Lderived=(TIncljets*)0x1000;
     {
       TObject *G__Lpbase=(TObject*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__fastnloDictLN_TIncljets),G__get_linked_tagnum(&G__fastnloDictLN_TObject),(long)G__Lpbase-(long)G__Lderived,1,1);
     }
   }
}

/*********************************************************
* typedef information setup/
*********************************************************/
extern "C" void G__cpp_setup_typetablefastnloDict() {

   /* Setting up typedef entry */
   G__search_typename2("Version_t",115,-1,0,
-1);
   G__setnewtype(-1,"Class version identifier (short)",0);
   G__search_typename2("vector<double>",117,G__get_linked_tagnum(&G__fastnloDictLN_vectorlEdoublecOallocatorlEdoublegRsPgR),0,-1);
   G__setnewtype(-1,"// @(#)root/base:$Name:  $:$Id: TROOT.h,v 1.40 2004/02/19 00:11:18 rdm Exp $",0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__fastnloDictLN_reverse_iteratorlEvectorlEdoublecOallocatorlEdoublegRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__fastnloDictLN_vectorlEdoublecOallocatorlEdoublegRsPgR));
   G__setnewtype(-1,"// @(#)root/base:$Name:  $:$Id: TROOT.h,v 1.40 2004/02/19 00:11:18 rdm Exp $",0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__fastnloDictLN_reverse_iteratorlEvectorlEdoublecOallocatorlEdoublegRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__fastnloDictLN_vectorlEdoublecOallocatorlEdoublegRsPgR));
   G__setnewtype(-1,"// @(#)root/base:$Name:  $:$Id: TROOT.h,v 1.40 2004/02/19 00:11:18 rdm Exp $",0);
   G__search_typename2("weight_dis",117,G__get_linked_tagnum(&G__fastnloDictLN_nlocLcLweightlE3gR),0,G__get_linked_tagnum(&G__fastnloDictLN_TIncljets));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<vector<double> >",117,G__get_linked_tagnum(&G__fastnloDictLN_vectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgR),0,-1);
   G__setnewtype(-1,"// @(#)root/base:$Name:  $:$Id: TROOT.h,v 1.40 2004/02/19 00:11:18 rdm Exp $",0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__fastnloDictLN_reverse_iteratorlEvectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__fastnloDictLN_vectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgR));
   G__setnewtype(-1,"// @(#)root/base:$Name:  $:$Id: TROOT.h,v 1.40 2004/02/19 00:11:18 rdm Exp $",0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__fastnloDictLN_reverse_iteratorlEvectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__fastnloDictLN_vectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgR));
   G__setnewtype(-1,"// @(#)root/base:$Name:  $:$Id: TROOT.h,v 1.40 2004/02/19 00:11:18 rdm Exp $",0);
   G__search_typename2("vector<vector<double,allocator<double> >>",117,G__get_linked_tagnum(&G__fastnloDictLN_vectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgR),0,-1);
   G__setnewtype(-1,"// @(#)root/base:$Name:  $:$Id: TROOT.h,v 1.40 2004/02/19 00:11:18 rdm Exp $",0);
   G__search_typename2("vector<weight_dis>",117,G__get_linked_tagnum(&G__fastnloDictLN_vectorlEnlocLcLweightlE3gRcOallocatorlEnlocLcLweightlE3gRsPgRsPgR),0,-1);
   G__setnewtype(-1,"// @(#)root/base:$Name:  $:$Id: TROOT.h,v 1.40 2004/02/19 00:11:18 rdm Exp $",0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__fastnloDictLN_reverse_iteratorlEvectorlEnlocLcLweightlE3gRcOallocatorlEnlocLcLweightlE3gRsPgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__fastnloDictLN_vectorlEnlocLcLweightlE3gRcOallocatorlEnlocLcLweightlE3gRsPgRsPgR));
   G__setnewtype(-1,"// @(#)root/base:$Name:  $:$Id: TROOT.h,v 1.40 2004/02/19 00:11:18 rdm Exp $",0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__fastnloDictLN_reverse_iteratorlEvectorlEnlocLcLweightlE3gRcOallocatorlEnlocLcLweightlE3gRsPgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__fastnloDictLN_vectorlEnlocLcLweightlE3gRcOallocatorlEnlocLcLweightlE3gRsPgRsPgR));
   G__setnewtype(-1,"// @(#)root/base:$Name:  $:$Id: TROOT.h,v 1.40 2004/02/19 00:11:18 rdm Exp $",0);
   G__search_typename2("vector<nlo::weight<3>>",117,G__get_linked_tagnum(&G__fastnloDictLN_vectorlEnlocLcLweightlE3gRcOallocatorlEnlocLcLweightlE3gRsPgRsPgR),0,-1);
   G__setnewtype(-1,"// @(#)root/base:$Name:  $:$Id: TROOT.h,v 1.40 2004/02/19 00:11:18 rdm Exp $",0);
   G__search_typename2("vector<vector<weight_dis> >",117,G__get_linked_tagnum(&G__fastnloDictLN_vectorlEvectorlEnlocLcLweightlE3gRcOallocatorlEnlocLcLweightlE3gRsPgRsPgRcOallocatorlEvectorlEnlocLcLweightlE3gRcOallocatorlEnlocLcLweightlE3gRsPgRsPgRsPgRsPgR),0,-1);
   G__setnewtype(-1,"// @(#)root/base:$Name:  $:$Id: TROOT.h,v 1.40 2004/02/19 00:11:18 rdm Exp $",0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__fastnloDictLN_reverse_iteratorlEvectorlEvectorlEnlocLcLweightlE3gRcOallocatorlEnlocLcLweightlE3gRsPgRsPgRcOallocatorlEvectorlEnlocLcLweightlE3gRcOallocatorlEnlocLcLweightlE3gRsPgRsPgRsPgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__fastnloDictLN_vectorlEvectorlEnlocLcLweightlE3gRcOallocatorlEnlocLcLweightlE3gRsPgRsPgRcOallocatorlEvectorlEnlocLcLweightlE3gRcOallocatorlEnlocLcLweightlE3gRsPgRsPgRsPgRsPgR));
   G__setnewtype(-1,"// @(#)root/base:$Name:  $:$Id: TROOT.h,v 1.40 2004/02/19 00:11:18 rdm Exp $",0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__fastnloDictLN_reverse_iteratorlEvectorlEvectorlEnlocLcLweightlE3gRcOallocatorlEnlocLcLweightlE3gRsPgRsPgRcOallocatorlEvectorlEnlocLcLweightlE3gRcOallocatorlEnlocLcLweightlE3gRsPgRsPgRsPgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__fastnloDictLN_vectorlEvectorlEnlocLcLweightlE3gRcOallocatorlEnlocLcLweightlE3gRsPgRsPgRcOallocatorlEvectorlEnlocLcLweightlE3gRcOallocatorlEnlocLcLweightlE3gRsPgRsPgRsPgRsPgR));
   G__setnewtype(-1,"// @(#)root/base:$Name:  $:$Id: TROOT.h,v 1.40 2004/02/19 00:11:18 rdm Exp $",0);
   G__search_typename2("vector<vector<nlo::weight<3>,allocator<nlo::weight<3> > >>",117,G__get_linked_tagnum(&G__fastnloDictLN_vectorlEvectorlEnlocLcLweightlE3gRcOallocatorlEnlocLcLweightlE3gRsPgRsPgRcOallocatorlEvectorlEnlocLcLweightlE3gRcOallocatorlEnlocLcLweightlE3gRsPgRsPgRsPgRsPgR),0,-1);
   G__setnewtype(-1,"// @(#)root/base:$Name:  $:$Id: TROOT.h,v 1.40 2004/02/19 00:11:18 rdm Exp $",0);
   G__search_typename2("vector<vector<vector<weight_dis> > >",117,G__get_linked_tagnum(&G__fastnloDictLN_vectorlEvectorlEvectorlEnlocLcLweightlE3gRcOallocatorlEnlocLcLweightlE3gRsPgRsPgRcOallocatorlEvectorlEnlocLcLweightlE3gRcOallocatorlEnlocLcLweightlE3gRsPgRsPgRsPgRsPgRcOallocatorlEvectorlEvectorlEnlocLcLweightlE3gRcOallocatorlEnlocLcLweightlE3gRsPgRsPgRcOallocatorlEvectorlEnlocLcLweightlE3gRcOallocatorlEnlocLcLweightlE3gRsPgRsPgRsPgRsPgRsPgRsPgR),0,-1);
   G__setnewtype(-1,"// @(#)root/base:$Name:  $:$Id: TROOT.h,v 1.40 2004/02/19 00:11:18 rdm Exp $",0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__fastnloDictLN_reverse_iteratorlEvectorlEvectorlEvectorlEnlocLcLweightlE3gRcOallocatorlEnlocLcLweightlE3gRsPgRsPgRcOallocatorlEvectorlEnlocLcLweightlE3gRcOallocatorlEnlocLcLweightlE3gRsPgRsPgRsPgRsPgRcOallocatorlEvectorlEvectorlEnlocLcLweightlE3gRcOallocatorlEnlocLcLweightlE3gRsPgRsPgRcOallocatorlEvectorlEnlocLcLweightlE3gRcOallocatorlEnlocLcLweightlE3gRsPgRsPgRsPgRsPgRsPgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__fastnloDictLN_vectorlEvectorlEvectorlEnlocLcLweightlE3gRcOallocatorlEnlocLcLweightlE3gRsPgRsPgRcOallocatorlEvectorlEnlocLcLweightlE3gRcOallocatorlEnlocLcLweightlE3gRsPgRsPgRsPgRsPgRcOallocatorlEvectorlEvectorlEnlocLcLweightlE3gRcOallocatorlEnlocLcLweightlE3gRsPgRsPgRcOallocatorlEvectorlEnlocLcLweightlE3gRcOallocatorlEnlocLcLweightlE3gRsPgRsPgRsPgRsPgRsPgRsPgR));
   G__setnewtype(-1,"// @(#)root/base:$Name:  $:$Id: TROOT.h,v 1.40 2004/02/19 00:11:18 rdm Exp $",0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__fastnloDictLN_reverse_iteratorlEvectorlEvectorlEvectorlEnlocLcLweightlE3gRcOallocatorlEnlocLcLweightlE3gRsPgRsPgRcOallocatorlEvectorlEnlocLcLweightlE3gRcOallocatorlEnlocLcLweightlE3gRsPgRsPgRsPgRsPgRcOallocatorlEvectorlEvectorlEnlocLcLweightlE3gRcOallocatorlEnlocLcLweightlE3gRsPgRsPgRcOallocatorlEvectorlEnlocLcLweightlE3gRcOallocatorlEnlocLcLweightlE3gRsPgRsPgRsPgRsPgRsPgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__fastnloDictLN_vectorlEvectorlEvectorlEnlocLcLweightlE3gRcOallocatorlEnlocLcLweightlE3gRsPgRsPgRcOallocatorlEvectorlEnlocLcLweightlE3gRcOallocatorlEnlocLcLweightlE3gRsPgRsPgRsPgRsPgRcOallocatorlEvectorlEvectorlEnlocLcLweightlE3gRcOallocatorlEnlocLcLweightlE3gRsPgRsPgRcOallocatorlEvectorlEnlocLcLweightlE3gRcOallocatorlEnlocLcLweightlE3gRsPgRsPgRsPgRsPgRsPgRsPgR));
   G__setnewtype(-1,"// @(#)root/base:$Name:  $:$Id: TROOT.h,v 1.40 2004/02/19 00:11:18 rdm Exp $",0);
   G__search_typename2("vector<vector<vector<nlo::weight<3>,allocator<nlo::weight<3> > >,allocator<vector<nlo::weight<3>,allocator<nlo::weight<3> > > > >>",117,G__get_linked_tagnum(&G__fastnloDictLN_vectorlEvectorlEvectorlEnlocLcLweightlE3gRcOallocatorlEnlocLcLweightlE3gRsPgRsPgRcOallocatorlEvectorlEnlocLcLweightlE3gRcOallocatorlEnlocLcLweightlE3gRsPgRsPgRsPgRsPgRcOallocatorlEvectorlEvectorlEnlocLcLweightlE3gRcOallocatorlEnlocLcLweightlE3gRsPgRsPgRcOallocatorlEvectorlEnlocLcLweightlE3gRcOallocatorlEnlocLcLweightlE3gRsPgRsPgRsPgRsPgRsPgRsPgR),0,-1);
   G__setnewtype(-1,"// @(#)root/base:$Name:  $:$Id: TROOT.h,v 1.40 2004/02/19 00:11:18 rdm Exp $",0);
   G__search_typename2("vector<vector<vector<vector<weight_dis> > > >",117,G__get_linked_tagnum(&G__fastnloDictLN_vectorlEvectorlEvectorlEvectorlEnlocLcLweightlE3gRcOallocatorlEnlocLcLweightlE3gRsPgRsPgRcOallocatorlEvectorlEnlocLcLweightlE3gRcOallocatorlEnlocLcLweightlE3gRsPgRsPgRsPgRsPgRcOallocatorlEvectorlEvectorlEnlocLcLweightlE3gRcOallocatorlEnlocLcLweightlE3gRsPgRsPgRcOallocatorlEvectorlEnlocLcLweightlE3gRcOallocatorlEnlocLcLweightlE3gRsPgRsPgRsPgRsPgRsPgRsPgRcOallocatorlEvectorlEvectorlEvectorlEnlocLcLweightlE3gRcOallocatorlEnlocLcLweightlE3gRsPgRsPgRcOallocatorlEvectorlEnlocLcLweightlE3gRcOallocatorlEnlocLcLweightlE3gRsPgRsPgRsPgRsPgRcOallocatorlEvectorlEvectorlEnlocLcLweightlE3gRcOallocatorlEnlocLcLweightlE3gRsPgRsPgRcOallocatorlEvectorlEnlocLcLweightlE3gRcOallocatorlEnlocLcLweightlE3gRsPgRsPgRsPgRsPgRsPgRsPgRsPgRsPgR),0,-1);
   G__setnewtype(-1,"// @(#)root/base:$Name:  $:$Id: TROOT.h,v 1.40 2004/02/19 00:11:18 rdm Exp $",0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__fastnloDictLN_reverse_iteratorlEvectorlEvectorlEvectorlEvectorlEnlocLcLweightlE3gRcOallocatorlEnlocLcLweightlE3gRsPgRsPgRcOallocatorlEvectorlEnlocLcLweightlE3gRcOallocatorlEnlocLcLweightlE3gRsPgRsPgRsPgRsPgRcOallocatorlEvectorlEvectorlEnlocLcLweightlE3gRcOallocatorlEnlocLcLweightlE3gRsPgRsPgRcOallocatorlEvectorlEnlocLcLweightlE3gRcOallocatorlEnlocLcLweightlE3gRsPgRsPgRsPgRsPgRsPgRsPgRcOallocatorlEvectorlEvectorlEvectorlEnlocLcLweightlE3gRcOallocatorlEnlocLcLweightlE3gRsPgRsPgRcOallocatorlEvectorlEnlocLcLweightlE3gRcOallocatorlEnlocLcLweightlE3gRsPgRsPgRsPgRsPgRcOallocatorlEvectorlEvectorlEnlocLcLweightlE3gRcOallocatorlEnlocLcLweightlE3gRsPgRsPgRcOallocatorlEvectorlEnlocLcLweightlE3gRcOallocatorlEnlocLcLweightlE3gRsPgRsPgRsPgRsPgRsPgRsPgRsPgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__fastnloDictLN_vectorlEvectorlEvectorlEvectorlEnlocLcLweightlE3gRcOallocatorlEnlocLcLweightlE3gRsPgRsPgRcOallocatorlEvectorlEnlocLcLweightlE3gRcOallocatorlEnlocLcLweightlE3gRsPgRsPgRsPgRsPgRcOallocatorlEvectorlEvectorlEnlocLcLweightlE3gRcOallocatorlEnlocLcLweightlE3gRsPgRsPgRcOallocatorlEvectorlEnlocLcLweightlE3gRcOallocatorlEnlocLcLweightlE3gRsPgRsPgRsPgRsPgRsPgRsPgRcOallocatorlEvectorlEvectorlEvectorlEnlocLcLweightlE3gRcOallocatorlEnlocLcLweightlE3gRsPgRsPgRcOallocatorlEvectorlEnlocLcLweightlE3gRcOallocatorlEnlocLcLweightlE3gRsPgRsPgRsPgRsPgRcOallocatorlEvectorlEvectorlEnlocLcLweightlE3gRcOallocatorlEnlocLcLweightlE3gRsPgRsPgRcOallocatorlEvectorlEnlocLcLweightlE3gRcOallocatorlEnlocLcLweightlE3gRsPgRsPgRsPgRsPgRsPgRsPgRsPgRsPgR));
   G__setnewtype(-1,"// @(#)root/base:$Name:  $:$Id: TROOT.h,v 1.40 2004/02/19 00:11:18 rdm Exp $",0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__fastnloDictLN_reverse_iteratorlEvectorlEvectorlEvectorlEvectorlEnlocLcLweightlE3gRcOallocatorlEnlocLcLweightlE3gRsPgRsPgRcOallocatorlEvectorlEnlocLcLweightlE3gRcOallocatorlEnlocLcLweightlE3gRsPgRsPgRsPgRsPgRcOallocatorlEvectorlEvectorlEnlocLcLweightlE3gRcOallocatorlEnlocLcLweightlE3gRsPgRsPgRcOallocatorlEvectorlEnlocLcLweightlE3gRcOallocatorlEnlocLcLweightlE3gRsPgRsPgRsPgRsPgRsPgRsPgRcOallocatorlEvectorlEvectorlEvectorlEnlocLcLweightlE3gRcOallocatorlEnlocLcLweightlE3gRsPgRsPgRcOallocatorlEvectorlEnlocLcLweightlE3gRcOallocatorlEnlocLcLweightlE3gRsPgRsPgRsPgRsPgRcOallocatorlEvectorlEvectorlEnlocLcLweightlE3gRcOallocatorlEnlocLcLweightlE3gRsPgRsPgRcOallocatorlEvectorlEnlocLcLweightlE3gRcOallocatorlEnlocLcLweightlE3gRsPgRsPgRsPgRsPgRsPgRsPgRsPgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__fastnloDictLN_vectorlEvectorlEvectorlEvectorlEnlocLcLweightlE3gRcOallocatorlEnlocLcLweightlE3gRsPgRsPgRcOallocatorlEvectorlEnlocLcLweightlE3gRcOallocatorlEnlocLcLweightlE3gRsPgRsPgRsPgRsPgRcOallocatorlEvectorlEvectorlEnlocLcLweightlE3gRcOallocatorlEnlocLcLweightlE3gRsPgRsPgRcOallocatorlEvectorlEnlocLcLweightlE3gRcOallocatorlEnlocLcLweightlE3gRsPgRsPgRsPgRsPgRsPgRsPgRcOallocatorlEvectorlEvectorlEvectorlEnlocLcLweightlE3gRcOallocatorlEnlocLcLweightlE3gRsPgRsPgRcOallocatorlEvectorlEnlocLcLweightlE3gRcOallocatorlEnlocLcLweightlE3gRsPgRsPgRsPgRsPgRcOallocatorlEvectorlEvectorlEnlocLcLweightlE3gRcOallocatorlEnlocLcLweightlE3gRsPgRsPgRcOallocatorlEvectorlEnlocLcLweightlE3gRcOallocatorlEnlocLcLweightlE3gRsPgRsPgRsPgRsPgRsPgRsPgRsPgRsPgR));
   G__setnewtype(-1,"// @(#)root/base:$Name:  $:$Id: TROOT.h,v 1.40 2004/02/19 00:11:18 rdm Exp $",0);
   G__search_typename2("vector<vector<vector<vector<nlo::weight<3>,allocator<nlo::weight<3> > >,allocator<vector<nlo::weight<3>,allocator<nlo::weight<3> > > > >,allocator<vector<vector<nlo::weight<3>,allocator<nlo::weight<3> > >,allocator<vector<nlo::weight<3>,allocator<nlo::weight<3> > > > > > >>",117,G__get_linked_tagnum(&G__fastnloDictLN_vectorlEvectorlEvectorlEvectorlEnlocLcLweightlE3gRcOallocatorlEnlocLcLweightlE3gRsPgRsPgRcOallocatorlEvectorlEnlocLcLweightlE3gRcOallocatorlEnlocLcLweightlE3gRsPgRsPgRsPgRsPgRcOallocatorlEvectorlEvectorlEnlocLcLweightlE3gRcOallocatorlEnlocLcLweightlE3gRsPgRsPgRcOallocatorlEvectorlEnlocLcLweightlE3gRcOallocatorlEnlocLcLweightlE3gRsPgRsPgRsPgRsPgRsPgRsPgRcOallocatorlEvectorlEvectorlEvectorlEnlocLcLweightlE3gRcOallocatorlEnlocLcLweightlE3gRsPgRsPgRcOallocatorlEvectorlEnlocLcLweightlE3gRcOallocatorlEnlocLcLweightlE3gRsPgRsPgRsPgRsPgRcOallocatorlEvectorlEvectorlEnlocLcLweightlE3gRcOallocatorlEnlocLcLweightlE3gRsPgRsPgRcOallocatorlEvectorlEnlocLcLweightlE3gRcOallocatorlEnlocLcLweightlE3gRsPgRsPgRsPgRsPgRsPgRsPgRsPgRsPgR),0,-1);
   G__setnewtype(-1,"// @(#)root/base:$Name:  $:$Id: TROOT.h,v 1.40 2004/02/19 00:11:18 rdm Exp $",0);
   G__search_typename2("vector<vector<vector<double> > >",117,G__get_linked_tagnum(&G__fastnloDictLN_vectorlEvectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgRcOallocatorlEvectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgRsPgRsPgR),0,-1);
   G__setnewtype(-1,"// @(#)root/base:$Name:  $:$Id: TROOT.h,v 1.40 2004/02/19 00:11:18 rdm Exp $",0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__fastnloDictLN_reverse_iteratorlEvectorlEvectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgRcOallocatorlEvectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgRsPgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__fastnloDictLN_vectorlEvectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgRcOallocatorlEvectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgRsPgRsPgR));
   G__setnewtype(-1,"// @(#)root/base:$Name:  $:$Id: TROOT.h,v 1.40 2004/02/19 00:11:18 rdm Exp $",0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__fastnloDictLN_reverse_iteratorlEvectorlEvectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgRcOallocatorlEvectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgRsPgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__fastnloDictLN_vectorlEvectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgRcOallocatorlEvectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgRsPgRsPgR));
   G__setnewtype(-1,"// @(#)root/base:$Name:  $:$Id: TROOT.h,v 1.40 2004/02/19 00:11:18 rdm Exp $",0);
   G__search_typename2("vector<vector<vector<double,allocator<double> >,allocator<vector<double,allocator<double> > > >>",117,G__get_linked_tagnum(&G__fastnloDictLN_vectorlEvectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgRcOallocatorlEvectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgRsPgRsPgR),0,-1);
   G__setnewtype(-1,"// @(#)root/base:$Name:  $:$Id: TROOT.h,v 1.40 2004/02/19 00:11:18 rdm Exp $",0);
}

/*********************************************************
* Data Member information setup/
*********************************************************/

   /* Setting up class,struct,union tag member variable */

   /* TIncljets */
static void G__setup_memvarTIncljets(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__fastnloDictLN_TIncljets));
   { TIncljets *p; p=(TIncljets*)0x1000; if (p) { }
   G__memvar_setup((void*)((long)(&p->nQ2)-(long)(p)),105,0,0,-1,-1,-1,1,"nQ2=",0,"No of Q2idity bins ");
   G__memvar_setup((void*)((long)(&p->Q2high)-(long)(p)),68,0,0,-1,-1,-1,1,"Q2high=",0,"[nQ2] array for Q2 boundaries");
   G__memvar_setup((void*)((long)(&p->npt)-(long)(p)),73,0,0,-1,-1,-1,1,"npt=",0,"[nQ2] No of pT bins in each Q2 range");
   G__memvar_setup((void*)((long)(&p->nptmax)-(long)(p)),105,0,0,-1,-1,-1,1,"nptmax=",0,"maximum number of pt bins");
   G__memvar_setup((void*)((long)(&p->pthigh)-(long)(p)),117,0,0,G__get_linked_tagnum(&G__fastnloDictLN_vectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgR),G__defined_typename("vector<vector<double> >"),-1,1,"pthigh=",0,"array for pT boundaries");
   G__memvar_setup((void*)((long)(&p->ptlow)-(long)(p)),100,0,0,-1,-1,-1,1,"ptlow=",0,"lowest pt considered ");
   G__memvar_setup((void*)((long)(&p->nscalevar)-(long)(p)),105,0,0,-1,-1,-1,1,"nscalevar=",0,"number of scale variations (mu_r, mu_f) for NLO");
   G__memvar_setup((void*)((long)(&p->murscale)-(long)(p)),117,0,0,G__get_linked_tagnum(&G__fastnloDictLN_vectorlEdoublecOallocatorlEdoublegRsPgR),G__defined_typename("vector<double>"),-1,1,"murscale=",0,"overall scale factor for renormalization scale");
   G__memvar_setup((void*)((long)(&p->murval)-(long)(p)),117,0,0,G__get_linked_tagnum(&G__fastnloDictLN_vectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgR),G__defined_typename("vector<vector<double> >"),-1,1,"murval=",0,"array for renormalization scale values");
   G__memvar_setup((void*)((long)(&p->mufscale)-(long)(p)),117,0,0,G__get_linked_tagnum(&G__fastnloDictLN_vectorlEdoublecOallocatorlEdoublegRsPgR),G__defined_typename("vector<double>"),-1,1,"mufscale=",0,"overall scale factor for factorization scale");
   G__memvar_setup((void*)((long)(&p->mufval)-(long)(p)),117,0,0,G__get_linked_tagnum(&G__fastnloDictLN_vectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgR),G__defined_typename("vector<vector<double> >"),-1,1,"mufval=",0,"array for factorization scale values");
   G__memvar_setup((void*)((long)(&p->ntot)-(long)(p)),105,0,0,-1,-1,-1,1,"ntot=",0,"no of xbins ");
   G__memvar_setup((void*)((long)(&p->xlimit)-(long)(p)),117,0,0,G__get_linked_tagnum(&G__fastnloDictLN_vectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgR),G__defined_typename("vector<vector<double> >"),-1,1,"xlimit=",0,"array for lower x limits");
   G__memvar_setup((void*)((long)(&p->disweights)-(long)(p)),117,0,0,G__get_linked_tagnum(&G__fastnloDictLN_vectorlEvectorlEvectorlEvectorlEnlocLcLweightlE3gRcOallocatorlEnlocLcLweightlE3gRsPgRsPgRcOallocatorlEvectorlEnlocLcLweightlE3gRcOallocatorlEnlocLcLweightlE3gRsPgRsPgRsPgRsPgRcOallocatorlEvectorlEvectorlEnlocLcLweightlE3gRcOallocatorlEnlocLcLweightlE3gRsPgRsPgRcOallocatorlEvectorlEnlocLcLweightlE3gRcOallocatorlEnlocLcLweightlE3gRsPgRsPgRsPgRsPgRsPgRsPgRcOallocatorlEvectorlEvectorlEvectorlEnlocLcLweightlE3gRcOallocatorlEnlocLcLweightlE3gRsPgRsPgRcOallocatorlEvectorlEnlocLcLweightlE3gRcOallocatorlEnlocLcLweightlE3gRsPgRsPgRsPgRsPgRcOallocatorlEvectorlEvectorlEnlocLcLweightlE3gRcOallocatorlEnlocLcLweightlE3gRsPgRsPgRcOallocatorlEvectorlEnlocLcLweightlE3gRcOallocatorlEnlocLcLweightlE3gRsPgRsPgRsPgRsPgRsPgRsPgRsPgRsPgR),G__defined_typename("vector<vector<vector<vector<weight_dis> > > >"),-1,1,"disweights=",0,"! array for the weights MAIN ARRAY");
   G__memvar_setup((void*)((long)(&p->pdf)-(long)(p)),117,0,0,G__get_linked_tagnum(&G__fastnloDictLN_vectorlEvectorlEvectorlEnlocLcLweightlE3gRcOallocatorlEnlocLcLweightlE3gRsPgRsPgRcOallocatorlEvectorlEnlocLcLweightlE3gRcOallocatorlEnlocLcLweightlE3gRsPgRsPgRsPgRsPgRcOallocatorlEvectorlEvectorlEnlocLcLweightlE3gRcOallocatorlEnlocLcLweightlE3gRsPgRsPgRcOallocatorlEvectorlEnlocLcLweightlE3gRcOallocatorlEnlocLcLweightlE3gRsPgRsPgRsPgRsPgRsPgRsPgR),G__defined_typename("vector<vector<vector<weight_dis> > >"),-1,1,"pdf=",0,"! array for the pdfs");
   G__memvar_setup((void*)((long)(&p->nsubproc)-(long)(p)),105,0,0,-1,-1,-1,1,"nsubproc=",0,"no of subprocesses");
   G__memvar_setup((void*)((long)(&p->nevents)-(long)(p)),117,0,0,G__get_linked_tagnum(&G__fastnloDictLN_vectorlEdoublecOallocatorlEdoublegRsPgR),G__defined_typename("vector<double>"),-1,1,"nevents=",0,"no of events calculated so far for each scale variation");
   G__memvar_setup((void*)((long)(&p->nwrite)-(long)(p)),105,0,0,-1,-1,-1,1,"nwrite=",0,"no of events after to write out the table");
   G__memvar_setup((void*)((long)(&p->ireaction)-(long)(p)),105,0,0,-1,-1,-1,1,"ireaction=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->s)-(long)(p)),100,0,0,-1,-1,-1,1,"s=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->iproc)-(long)(p)),105,0,0,-1,-1,-1,1,"iproc=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->ialgo)-(long)(p)),105,0,0,-1,-1,-1,1,"ialgo=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->JetResol1)-(long)(p)),100,0,0,-1,-1,-1,1,"JetResol1=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->JetResol2)-(long)(p)),100,0,0,-1,-1,-1,1,"JetResol2=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->npow)-(long)(p)),105,0,0,-1,-1,-1,1,"npow=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->npowmax)-(long)(p)),105,0,0,-1,-1,-1,1,"npowmax=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->Oalphas)-(long)(p)),105,0,0,-1,-1,-1,1,"Oalphas=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->ixscheme)-(long)(p)),105,0,0,-1,-1,-1,1,"ixscheme=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->ipdfwgt)-(long)(p)),105,0,0,-1,-1,-1,1,"ipdfwgt=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->xsection)-(long)(p)),117,0,0,G__get_linked_tagnum(&G__fastnloDictLN_vectorlEvectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgRcOallocatorlEvectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgRsPgRsPgR),G__defined_typename("vector<vector<vector<double> > >"),-1,1,"xsection=",0,"the result");
   G__memvar_setup((void*)((long)(&p->q2binning)-(long)(p)),100,0,0,-1,-1,-1,1,"q2binning[5]=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->ptbinning)-(long)(p)),100,0,0,-1,-1,-1,1,"ptbinning[5]=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->rebinned)-(long)(p)),117,0,0,G__get_linked_tagnum(&G__fastnloDictLN_vectorlEvectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgRcOallocatorlEvectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgRsPgRsPgR),G__defined_typename("vector<vector<vector<double> > >"),-1,1,"rebinned=",0,"the result");
   G__memvar_setup((void*)((long)(&p->reference)-(long)(p)),117,0,0,G__get_linked_tagnum(&G__fastnloDictLN_vectorlEvectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgRcOallocatorlEvectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgRsPgRsPgR),G__defined_typename("vector<vector<vector<double> > >"),-1,1,"reference=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->lhapdf)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__fastnloDictLN_LHAPDFWrap),-1,-1,1,"lhapdf=",0,(char*)NULL);
   G__memvar_setup((void*)NULL,85,0,0,G__get_linked_tagnum(&G__fastnloDictLN_TClass),-1,-2,4,"fgIsA=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}

extern "C" void G__cpp_setup_memvarfastnloDict() {
}
/***********************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
***********************************************************/

/*********************************************************
* Member function information setup for each class
*********************************************************/
static void G__setup_memfuncTIncljets(void) {
   /* TIncljets */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__fastnloDictLN_TIncljets));
   G__memfunc_setup("TIncljets",912,G__fastnloDict_137_1_0,105,G__get_linked_tagnum(&G__fastnloDictLN_TIncljets),-1,0,0,1,1,0,"",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("alphas",633,G__fastnloDict_137_2_0,100,-1,-1,0,2,1,1,0,
"d - - 0 - Q d - - 0 - alphasMZ",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("ReadTable",868,G__fastnloDict_137_3_0,121,-1,-1,0,1,1,1,0,"u 'string' - 0 - filename",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("ReadPDF",598,G__fastnloDict_137_4_0,121,-1,-1,0,1,1,1,0,"u 'string' - 0 - filename",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("SetPDFSet",818,G__fastnloDict_137_5_0,121,-1,-1,0,1,1,1,0,"i - - 0 - set",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("FillPDFCache",1077,G__fastnloDict_137_6_0,121,-1,-1,0,1,1,1,0,"d - - 0 - muffactor",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("ResetXsection",1360,G__fastnloDict_137_7_0,121,-1,-1,0,0,1,1,0,"",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("CalcXsection",1216,G__fastnloDict_137_8_0,121,-1,-1,0,2,1,1,0,
"d - - 0 - asmz i - - 0 0 scale",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("GetXsection",1133,G__fastnloDict_137_9_0,100,-1,-1,0,3,1,1,0,
"i - - 0 - Q2 i - - 0 - pt "
"i - - 0 - order",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("Rebin",496,G__fastnloDict_137_0_1,121,-1,-1,0,0,1,1,0,"",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("GetRebinned",1095,G__fastnloDict_137_1_1,100,-1,-1,0,3,1,1,0,
"i - - 0 - Q2 i - - 0 - pt "
"i - - 0 - order",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("ResetReference",1426,G__fastnloDict_137_2_1,121,-1,-1,0,0,1,1,0,"",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("ReadReference",1291,G__fastnloDict_137_3_1,121,-1,-1,0,2,1,1,0,
"u 'string' - 0 - filename i - - 0 - order",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("GetReference",1199,G__fastnloDict_137_4_1,100,-1,-1,0,3,1,1,0,
"i - - 0 - Q2 i - - 0 - pt "
"i - - 0 - order",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("Class",502,G__fastnloDict_137_5_1,85,G__get_linked_tagnum(&G__fastnloDictLN_TClass),-1,0,0,3,1,0,"",(char*)NULL,(void*)(TClass* (*)())(&TIncljets::Class),0);
   G__memfunc_setup("Class_Name",982,G__fastnloDict_137_6_1,67,-1,-1,0,0,3,1,1,"",(char*)NULL,(void*)(const char* (*)())(&TIncljets::Class_Name),0);
   G__memfunc_setup("Class_Version",1339,G__fastnloDict_137_7_1,115,-1,G__defined_typename("Version_t"),0,0,3,1,0,"",(char*)NULL,(void*)(Version_t (*)())(&TIncljets::Class_Version),0);
   G__memfunc_setup("Dictionary",1046,G__fastnloDict_137_8_1,121,-1,-1,0,0,3,1,0,"",(char*)NULL,(void*)(void (*)())(&TIncljets::Dictionary),0);
   G__memfunc_setup("IsA",253,G__fastnloDict_137_9_1,85,G__get_linked_tagnum(&G__fastnloDictLN_TClass),-1,0,0,1,1,8,"",(char*)NULL,(void*)NULL,1);
   G__memfunc_setup("ShowMembers",1132,G__fastnloDict_137_0_2,121,-1,-1,0,2,1,1,0,
"u 'TMemberInspector' - 1 - insp C - - 0 - parent",(char*)NULL,(void*)NULL,1);
   G__memfunc_setup("Streamer",835,G__fastnloDict_137_1_2,121,-1,-1,0,1,1,1,0,"u 'TBuffer' - 1 - b",(char*)NULL,(void*)NULL,1);
   G__memfunc_setup("StreamerNVirtual",1656,G__fastnloDict_137_2_2,121,-1,-1,0,1,1,1,0,"u 'TBuffer' - 1 - b",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("DeclFileName",1145,G__fastnloDict_137_3_2,67,-1,-1,0,0,3,1,1,"",(char*)NULL,(void*)(const char* (*)())(&TIncljets::DeclFileName),0);
   G__memfunc_setup("ImplFileLine",1178,G__fastnloDict_137_4_2,105,-1,-1,0,0,3,1,0,"",(char*)NULL,(void*)(int (*)())(&TIncljets::ImplFileLine),0);
   G__memfunc_setup("ImplFileName",1171,G__fastnloDict_137_5_2,67,-1,-1,0,0,3,1,1,"",(char*)NULL,(void*)(const char* (*)())(&TIncljets::ImplFileName),0);
   G__memfunc_setup("DeclFileLine",1152,G__fastnloDict_137_6_2,105,-1,-1,0,0,3,1,0,"",(char*)NULL,(void*)(int (*)())(&TIncljets::DeclFileLine),0);
   // automatic copy constructor
   G__memfunc_setup("TIncljets",912,G__fastnloDict_137_7_2,(int)('i'),G__get_linked_tagnum(&G__fastnloDictLN_TIncljets),-1,0,1,1,1,0,"u 'TIncljets' - 11 - -",(char*)NULL,(void*)NULL,0);
   // automatic destructor
   G__memfunc_setup("~TIncljets",1038,G__fastnloDict_137_8_2,(int)('y'),-1,-1,0,0,1,1,0,"",(char*)NULL,(void*)NULL,0);
   // automatic assignment operator
   G__memfunc_setup("operator=",937,G__fastnloDict_137_9_2,(int)('u'),G__get_linked_tagnum(&G__fastnloDictLN_TIncljets),-1,1,1,1,1,0,"u 'TIncljets' - 11 - -",(char*)NULL,(void*)NULL,0);
   G__tag_memfunc_reset();
}


/*********************************************************
* Member function information setup
*********************************************************/
extern "C" void G__cpp_setup_memfuncfastnloDict() {
}

/*********************************************************
* Global variable information setup for each class
*********************************************************/
static void G__cpp_setup_global0() {

   /* Setting up global variables */
   G__resetplocal();

}

static void G__cpp_setup_global1() {

   G__resetglobalenv();
}
extern "C" void G__cpp_setup_globalfastnloDict() {
  G__cpp_setup_global0();
  G__cpp_setup_global1();
}

/*********************************************************
* Global function information setup for each class
*********************************************************/
static void G__cpp_setup_func0() {
   G__lastifuncposition();

}

static void G__cpp_setup_func1() {
}

static void G__cpp_setup_func2() {
}

static void G__cpp_setup_func3() {
}

static void G__cpp_setup_func4() {
}

static void G__cpp_setup_func5() {
}

static void G__cpp_setup_func6() {
}

static void G__cpp_setup_func7() {

   G__resetifuncposition();
}

extern "C" void G__cpp_setup_funcfastnloDict() {
  G__cpp_setup_func0();
  G__cpp_setup_func1();
  G__cpp_setup_func2();
  G__cpp_setup_func3();
  G__cpp_setup_func4();
  G__cpp_setup_func5();
  G__cpp_setup_func6();
  G__cpp_setup_func7();
}

/*********************************************************
* Class,struct,union,enum tag information setup
*********************************************************/
/* Setup class/struct taginfo */
G__linked_taginfo G__fastnloDictLN_TClass = { "TClass" , 99 , -1 };
G__linked_taginfo G__fastnloDictLN_TBuffer = { "TBuffer" , 99 , -1 };
G__linked_taginfo G__fastnloDictLN_TMemberInspector = { "TMemberInspector" , 99 , -1 };
G__linked_taginfo G__fastnloDictLN_TObject = { "TObject" , 99 , -1 };
G__linked_taginfo G__fastnloDictLN_string = { "string" , 99 , -1 };
G__linked_taginfo G__fastnloDictLN_nlo = { "nlo" , 110 , -1 };
G__linked_taginfo G__fastnloDictLN_LHAPDFWrap = { "LHAPDFWrap" , 99 , -1 };
G__linked_taginfo G__fastnloDictLN_vectorlEdoublecOallocatorlEdoublegRsPgR = { "vector<double,allocator<double> >" , 99 , -1 };
G__linked_taginfo G__fastnloDictLN_reverse_iteratorlEvectorlEdoublecOallocatorlEdoublegRsPgRcLcLiteratorgR = { "reverse_iterator<vector<double,allocator<double> >::iterator>" , 99 , -1 };
G__linked_taginfo G__fastnloDictLN_TIncljets = { "TIncljets" , 99 , -1 };
G__linked_taginfo G__fastnloDictLN_nlocLcLweightlE3gR = { "nlo::weight<3>" , 99 , -1 };
G__linked_taginfo G__fastnloDictLN_vectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgR = { "vector<vector<double,allocator<double> >,allocator<vector<double,allocator<double> > > >" , 99 , -1 };
G__linked_taginfo G__fastnloDictLN_reverse_iteratorlEvectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<vector<double,allocator<double> >,allocator<vector<double,allocator<double> > > >::iterator>" , 99 , -1 };
G__linked_taginfo G__fastnloDictLN_vectorlEnlocLcLweightlE3gRcOallocatorlEnlocLcLweightlE3gRsPgRsPgR = { "vector<nlo::weight<3>,allocator<nlo::weight<3> > >" , 99 , -1 };
G__linked_taginfo G__fastnloDictLN_reverse_iteratorlEvectorlEnlocLcLweightlE3gRcOallocatorlEnlocLcLweightlE3gRsPgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<nlo::weight<3>,allocator<nlo::weight<3> > >::iterator>" , 99 , -1 };
G__linked_taginfo G__fastnloDictLN_vectorlEvectorlEnlocLcLweightlE3gRcOallocatorlEnlocLcLweightlE3gRsPgRsPgRcOallocatorlEvectorlEnlocLcLweightlE3gRcOallocatorlEnlocLcLweightlE3gRsPgRsPgRsPgRsPgR = { "vector<vector<nlo::weight<3>,allocator<nlo::weight<3> > >,allocator<vector<nlo::weight<3>,allocator<nlo::weight<3> > > > >" , 99 , -1 };
G__linked_taginfo G__fastnloDictLN_reverse_iteratorlEvectorlEvectorlEnlocLcLweightlE3gRcOallocatorlEnlocLcLweightlE3gRsPgRsPgRcOallocatorlEvectorlEnlocLcLweightlE3gRcOallocatorlEnlocLcLweightlE3gRsPgRsPgRsPgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<vector<nlo::weight<3>,allocator<nlo::weight<3> > >,allocator<vector<nlo::weight<3>,allocator<nlo::weight<3> > > > >::iterator>" , 99 , -1 };
G__linked_taginfo G__fastnloDictLN_vectorlEvectorlEvectorlEnlocLcLweightlE3gRcOallocatorlEnlocLcLweightlE3gRsPgRsPgRcOallocatorlEvectorlEnlocLcLweightlE3gRcOallocatorlEnlocLcLweightlE3gRsPgRsPgRsPgRsPgRcOallocatorlEvectorlEvectorlEnlocLcLweightlE3gRcOallocatorlEnlocLcLweightlE3gRsPgRsPgRcOallocatorlEvectorlEnlocLcLweightlE3gRcOallocatorlEnlocLcLweightlE3gRsPgRsPgRsPgRsPgRsPgRsPgR = { "vector<vector<vector<nlo::weight<3>,allocator<nlo::weight<3> > >,allocator<vector<nlo::weight<3>,allocator<nlo::weight<3> > > > >,allocator<vector<vector<nlo::weight<3>,allocator<nlo::weight<3> > >,allocator<vector<nlo::weight<3>,allocator<nlo::weight<3> > > > > > >" , 99 , -1 };
G__linked_taginfo G__fastnloDictLN_reverse_iteratorlEvectorlEvectorlEvectorlEnlocLcLweightlE3gRcOallocatorlEnlocLcLweightlE3gRsPgRsPgRcOallocatorlEvectorlEnlocLcLweightlE3gRcOallocatorlEnlocLcLweightlE3gRsPgRsPgRsPgRsPgRcOallocatorlEvectorlEvectorlEnlocLcLweightlE3gRcOallocatorlEnlocLcLweightlE3gRsPgRsPgRcOallocatorlEvectorlEnlocLcLweightlE3gRcOallocatorlEnlocLcLweightlE3gRsPgRsPgRsPgRsPgRsPgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<vector<vector<nlo::weight<3>,allocator<nlo::weight<3> > >,allocator<vector<nlo::weight<3>,allocator<nlo::weight<3> > > > >,allocator<vector<vector<nlo::weight<3>,allocator<nlo::weight<3> > >,allocator<vector<nlo::weight<3>,allocator<nlo::weight<3> > > > > > >::iterator>" , 99 , -1 };
G__linked_taginfo G__fastnloDictLN_vectorlEvectorlEvectorlEvectorlEnlocLcLweightlE3gRcOallocatorlEnlocLcLweightlE3gRsPgRsPgRcOallocatorlEvectorlEnlocLcLweightlE3gRcOallocatorlEnlocLcLweightlE3gRsPgRsPgRsPgRsPgRcOallocatorlEvectorlEvectorlEnlocLcLweightlE3gRcOallocatorlEnlocLcLweightlE3gRsPgRsPgRcOallocatorlEvectorlEnlocLcLweightlE3gRcOallocatorlEnlocLcLweightlE3gRsPgRsPgRsPgRsPgRsPgRsPgRcOallocatorlEvectorlEvectorlEvectorlEnlocLcLweightlE3gRcOallocatorlEnlocLcLweightlE3gRsPgRsPgRcOallocatorlEvectorlEnlocLcLweightlE3gRcOallocatorlEnlocLcLweightlE3gRsPgRsPgRsPgRsPgRcOallocatorlEvectorlEvectorlEnlocLcLweightlE3gRcOallocatorlEnlocLcLweightlE3gRsPgRsPgRcOallocatorlEvectorlEnlocLcLweightlE3gRcOallocatorlEnlocLcLweightlE3gRsPgRsPgRsPgRsPgRsPgRsPgRsPgRsPgR = { "vector<vector<vector<vector<nlo::weight<3>,allocator<nlo::weight<3> > >,allocator<vector<nlo::weight<3>,allocator<nlo::weight<3> > > > >,allocator<vector<vector<nlo::weight<3>,allocator<nlo::weight<3> > >,allocator<vector<nlo::weight<3>,allocator<nlo::weight<3> > > > > > >,allocator<vector<vector<vector<nlo::weight<3>,allocator<nlo::weight<3> > >,allocator<vector<nlo::weight<3>,allocator<nlo::weight<3> > > > >,allocator<vector<vector<nlo::weight<3>,allocator<nlo::weight<3> > >,allocator<vector<nlo::weight<3>,allocator<nlo::weight<3> > > > > > > > >" , 99 , -1 };
G__linked_taginfo G__fastnloDictLN_reverse_iteratorlEvectorlEvectorlEvectorlEvectorlEnlocLcLweightlE3gRcOallocatorlEnlocLcLweightlE3gRsPgRsPgRcOallocatorlEvectorlEnlocLcLweightlE3gRcOallocatorlEnlocLcLweightlE3gRsPgRsPgRsPgRsPgRcOallocatorlEvectorlEvectorlEnlocLcLweightlE3gRcOallocatorlEnlocLcLweightlE3gRsPgRsPgRcOallocatorlEvectorlEnlocLcLweightlE3gRcOallocatorlEnlocLcLweightlE3gRsPgRsPgRsPgRsPgRsPgRsPgRcOallocatorlEvectorlEvectorlEvectorlEnlocLcLweightlE3gRcOallocatorlEnlocLcLweightlE3gRsPgRsPgRcOallocatorlEvectorlEnlocLcLweightlE3gRcOallocatorlEnlocLcLweightlE3gRsPgRsPgRsPgRsPgRcOallocatorlEvectorlEvectorlEnlocLcLweightlE3gRcOallocatorlEnlocLcLweightlE3gRsPgRsPgRcOallocatorlEvectorlEnlocLcLweightlE3gRcOallocatorlEnlocLcLweightlE3gRsPgRsPgRsPgRsPgRsPgRsPgRsPgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<vector<vector<vector<nlo::weight<3>,allocator<nlo::weight<3> > >,allocator<vector<nlo::weight<3>,allocator<nlo::weight<3> > > > >,allocator<vector<vector<nlo::weight<3>,allocator<nlo::weight<3> > >,allocator<vector<nlo::weight<3>,allocator<nlo::weight<3> > > > > > >,allocator<vector<vector<vector<nlo::weight<3>,allocator<nlo::weight<3> > >,allocator<vector<nlo::weight<3>,allocator<nlo::weight<3> > > > >,allocator<vector<vector<nlo::weight<3>,allocator<nlo::weight<3> > >,allocator<vector<nlo::weight<3>,allocator<nlo::weight<3> > > > > > > > >::iterator>" , 99 , -1 };
G__linked_taginfo G__fastnloDictLN_vectorlEvectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgRcOallocatorlEvectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgRsPgRsPgR = { "vector<vector<vector<double,allocator<double> >,allocator<vector<double,allocator<double> > > >,allocator<vector<vector<double,allocator<double> >,allocator<vector<double,allocator<double> > > > > >" , 99 , -1 };
G__linked_taginfo G__fastnloDictLN_reverse_iteratorlEvectorlEvectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgRcOallocatorlEvectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgRsPgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<vector<vector<double,allocator<double> >,allocator<vector<double,allocator<double> > > >,allocator<vector<vector<double,allocator<double> >,allocator<vector<double,allocator<double> > > > > >::iterator>" , 99 , -1 };

/* Reset class/struct taginfo */
extern "C" void G__cpp_reset_tagtablefastnloDict() {
  G__fastnloDictLN_TClass.tagnum = -1 ;
  G__fastnloDictLN_TBuffer.tagnum = -1 ;
  G__fastnloDictLN_TMemberInspector.tagnum = -1 ;
  G__fastnloDictLN_TObject.tagnum = -1 ;
  G__fastnloDictLN_string.tagnum = -1 ;
  G__fastnloDictLN_nlo.tagnum = -1 ;
  G__fastnloDictLN_LHAPDFWrap.tagnum = -1 ;
  G__fastnloDictLN_vectorlEdoublecOallocatorlEdoublegRsPgR.tagnum = -1 ;
  G__fastnloDictLN_reverse_iteratorlEvectorlEdoublecOallocatorlEdoublegRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__fastnloDictLN_TIncljets.tagnum = -1 ;
  G__fastnloDictLN_nlocLcLweightlE3gR.tagnum = -1 ;
  G__fastnloDictLN_vectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgR.tagnum = -1 ;
  G__fastnloDictLN_reverse_iteratorlEvectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__fastnloDictLN_vectorlEnlocLcLweightlE3gRcOallocatorlEnlocLcLweightlE3gRsPgRsPgR.tagnum = -1 ;
  G__fastnloDictLN_reverse_iteratorlEvectorlEnlocLcLweightlE3gRcOallocatorlEnlocLcLweightlE3gRsPgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__fastnloDictLN_vectorlEvectorlEnlocLcLweightlE3gRcOallocatorlEnlocLcLweightlE3gRsPgRsPgRcOallocatorlEvectorlEnlocLcLweightlE3gRcOallocatorlEnlocLcLweightlE3gRsPgRsPgRsPgRsPgR.tagnum = -1 ;
  G__fastnloDictLN_reverse_iteratorlEvectorlEvectorlEnlocLcLweightlE3gRcOallocatorlEnlocLcLweightlE3gRsPgRsPgRcOallocatorlEvectorlEnlocLcLweightlE3gRcOallocatorlEnlocLcLweightlE3gRsPgRsPgRsPgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__fastnloDictLN_vectorlEvectorlEvectorlEnlocLcLweightlE3gRcOallocatorlEnlocLcLweightlE3gRsPgRsPgRcOallocatorlEvectorlEnlocLcLweightlE3gRcOallocatorlEnlocLcLweightlE3gRsPgRsPgRsPgRsPgRcOallocatorlEvectorlEvectorlEnlocLcLweightlE3gRcOallocatorlEnlocLcLweightlE3gRsPgRsPgRcOallocatorlEvectorlEnlocLcLweightlE3gRcOallocatorlEnlocLcLweightlE3gRsPgRsPgRsPgRsPgRsPgRsPgR.tagnum = -1 ;
  G__fastnloDictLN_reverse_iteratorlEvectorlEvectorlEvectorlEnlocLcLweightlE3gRcOallocatorlEnlocLcLweightlE3gRsPgRsPgRcOallocatorlEvectorlEnlocLcLweightlE3gRcOallocatorlEnlocLcLweightlE3gRsPgRsPgRsPgRsPgRcOallocatorlEvectorlEvectorlEnlocLcLweightlE3gRcOallocatorlEnlocLcLweightlE3gRsPgRsPgRcOallocatorlEvectorlEnlocLcLweightlE3gRcOallocatorlEnlocLcLweightlE3gRsPgRsPgRsPgRsPgRsPgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__fastnloDictLN_vectorlEvectorlEvectorlEvectorlEnlocLcLweightlE3gRcOallocatorlEnlocLcLweightlE3gRsPgRsPgRcOallocatorlEvectorlEnlocLcLweightlE3gRcOallocatorlEnlocLcLweightlE3gRsPgRsPgRsPgRsPgRcOallocatorlEvectorlEvectorlEnlocLcLweightlE3gRcOallocatorlEnlocLcLweightlE3gRsPgRsPgRcOallocatorlEvectorlEnlocLcLweightlE3gRcOallocatorlEnlocLcLweightlE3gRsPgRsPgRsPgRsPgRsPgRsPgRcOallocatorlEvectorlEvectorlEvectorlEnlocLcLweightlE3gRcOallocatorlEnlocLcLweightlE3gRsPgRsPgRcOallocatorlEvectorlEnlocLcLweightlE3gRcOallocatorlEnlocLcLweightlE3gRsPgRsPgRsPgRsPgRcOallocatorlEvectorlEvectorlEnlocLcLweightlE3gRcOallocatorlEnlocLcLweightlE3gRsPgRsPgRcOallocatorlEvectorlEnlocLcLweightlE3gRcOallocatorlEnlocLcLweightlE3gRsPgRsPgRsPgRsPgRsPgRsPgRsPgRsPgR.tagnum = -1 ;
  G__fastnloDictLN_reverse_iteratorlEvectorlEvectorlEvectorlEvectorlEnlocLcLweightlE3gRcOallocatorlEnlocLcLweightlE3gRsPgRsPgRcOallocatorlEvectorlEnlocLcLweightlE3gRcOallocatorlEnlocLcLweightlE3gRsPgRsPgRsPgRsPgRcOallocatorlEvectorlEvectorlEnlocLcLweightlE3gRcOallocatorlEnlocLcLweightlE3gRsPgRsPgRcOallocatorlEvectorlEnlocLcLweightlE3gRcOallocatorlEnlocLcLweightlE3gRsPgRsPgRsPgRsPgRsPgRsPgRcOallocatorlEvectorlEvectorlEvectorlEnlocLcLweightlE3gRcOallocatorlEnlocLcLweightlE3gRsPgRsPgRcOallocatorlEvectorlEnlocLcLweightlE3gRcOallocatorlEnlocLcLweightlE3gRsPgRsPgRsPgRsPgRcOallocatorlEvectorlEvectorlEnlocLcLweightlE3gRcOallocatorlEnlocLcLweightlE3gRsPgRsPgRcOallocatorlEvectorlEnlocLcLweightlE3gRcOallocatorlEnlocLcLweightlE3gRsPgRsPgRsPgRsPgRsPgRsPgRsPgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__fastnloDictLN_vectorlEvectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgRcOallocatorlEvectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgRsPgRsPgR.tagnum = -1 ;
  G__fastnloDictLN_reverse_iteratorlEvectorlEvectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgRcOallocatorlEvectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgRsPgRsPgRcLcLiteratorgR.tagnum = -1 ;
}


extern "C" void G__cpp_setup_tagtablefastnloDict() {

   /* Setting up class,struct,union tag entry */
   G__get_linked_tagnum(&G__fastnloDictLN_TClass);
   G__get_linked_tagnum(&G__fastnloDictLN_TBuffer);
   G__get_linked_tagnum(&G__fastnloDictLN_TMemberInspector);
   G__get_linked_tagnum(&G__fastnloDictLN_TObject);
   G__get_linked_tagnum(&G__fastnloDictLN_string);
   G__get_linked_tagnum(&G__fastnloDictLN_nlo);
   G__get_linked_tagnum(&G__fastnloDictLN_LHAPDFWrap);
   G__get_linked_tagnum(&G__fastnloDictLN_vectorlEdoublecOallocatorlEdoublegRsPgR);
   G__get_linked_tagnum(&G__fastnloDictLN_reverse_iteratorlEvectorlEdoublecOallocatorlEdoublegRsPgRcLcLiteratorgR);
   G__tagtable_setup(G__get_linked_tagnum(&G__fastnloDictLN_TIncljets),sizeof(TIncljets),-1,28928,(char*)NULL,G__setup_memvarTIncljets,G__setup_memfuncTIncljets);
   G__get_linked_tagnum(&G__fastnloDictLN_nlocLcLweightlE3gR);
   G__get_linked_tagnum(&G__fastnloDictLN_vectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgR);
   G__get_linked_tagnum(&G__fastnloDictLN_reverse_iteratorlEvectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum(&G__fastnloDictLN_vectorlEnlocLcLweightlE3gRcOallocatorlEnlocLcLweightlE3gRsPgRsPgR);
   G__get_linked_tagnum(&G__fastnloDictLN_reverse_iteratorlEvectorlEnlocLcLweightlE3gRcOallocatorlEnlocLcLweightlE3gRsPgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum(&G__fastnloDictLN_vectorlEvectorlEnlocLcLweightlE3gRcOallocatorlEnlocLcLweightlE3gRsPgRsPgRcOallocatorlEvectorlEnlocLcLweightlE3gRcOallocatorlEnlocLcLweightlE3gRsPgRsPgRsPgRsPgR);
   G__get_linked_tagnum(&G__fastnloDictLN_reverse_iteratorlEvectorlEvectorlEnlocLcLweightlE3gRcOallocatorlEnlocLcLweightlE3gRsPgRsPgRcOallocatorlEvectorlEnlocLcLweightlE3gRcOallocatorlEnlocLcLweightlE3gRsPgRsPgRsPgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum(&G__fastnloDictLN_vectorlEvectorlEvectorlEnlocLcLweightlE3gRcOallocatorlEnlocLcLweightlE3gRsPgRsPgRcOallocatorlEvectorlEnlocLcLweightlE3gRcOallocatorlEnlocLcLweightlE3gRsPgRsPgRsPgRsPgRcOallocatorlEvectorlEvectorlEnlocLcLweightlE3gRcOallocatorlEnlocLcLweightlE3gRsPgRsPgRcOallocatorlEvectorlEnlocLcLweightlE3gRcOallocatorlEnlocLcLweightlE3gRsPgRsPgRsPgRsPgRsPgRsPgR);
   G__get_linked_tagnum(&G__fastnloDictLN_reverse_iteratorlEvectorlEvectorlEvectorlEnlocLcLweightlE3gRcOallocatorlEnlocLcLweightlE3gRsPgRsPgRcOallocatorlEvectorlEnlocLcLweightlE3gRcOallocatorlEnlocLcLweightlE3gRsPgRsPgRsPgRsPgRcOallocatorlEvectorlEvectorlEnlocLcLweightlE3gRcOallocatorlEnlocLcLweightlE3gRsPgRsPgRcOallocatorlEvectorlEnlocLcLweightlE3gRcOallocatorlEnlocLcLweightlE3gRsPgRsPgRsPgRsPgRsPgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum(&G__fastnloDictLN_vectorlEvectorlEvectorlEvectorlEnlocLcLweightlE3gRcOallocatorlEnlocLcLweightlE3gRsPgRsPgRcOallocatorlEvectorlEnlocLcLweightlE3gRcOallocatorlEnlocLcLweightlE3gRsPgRsPgRsPgRsPgRcOallocatorlEvectorlEvectorlEnlocLcLweightlE3gRcOallocatorlEnlocLcLweightlE3gRsPgRsPgRcOallocatorlEvectorlEnlocLcLweightlE3gRcOallocatorlEnlocLcLweightlE3gRsPgRsPgRsPgRsPgRsPgRsPgRcOallocatorlEvectorlEvectorlEvectorlEnlocLcLweightlE3gRcOallocatorlEnlocLcLweightlE3gRsPgRsPgRcOallocatorlEvectorlEnlocLcLweightlE3gRcOallocatorlEnlocLcLweightlE3gRsPgRsPgRsPgRsPgRcOallocatorlEvectorlEvectorlEnlocLcLweightlE3gRcOallocatorlEnlocLcLweightlE3gRsPgRsPgRcOallocatorlEvectorlEnlocLcLweightlE3gRcOallocatorlEnlocLcLweightlE3gRsPgRsPgRsPgRsPgRsPgRsPgRsPgRsPgR);
   G__get_linked_tagnum(&G__fastnloDictLN_reverse_iteratorlEvectorlEvectorlEvectorlEvectorlEnlocLcLweightlE3gRcOallocatorlEnlocLcLweightlE3gRsPgRsPgRcOallocatorlEvectorlEnlocLcLweightlE3gRcOallocatorlEnlocLcLweightlE3gRsPgRsPgRsPgRsPgRcOallocatorlEvectorlEvectorlEnlocLcLweightlE3gRcOallocatorlEnlocLcLweightlE3gRsPgRsPgRcOallocatorlEvectorlEnlocLcLweightlE3gRcOallocatorlEnlocLcLweightlE3gRsPgRsPgRsPgRsPgRsPgRsPgRcOallocatorlEvectorlEvectorlEvectorlEnlocLcLweightlE3gRcOallocatorlEnlocLcLweightlE3gRsPgRsPgRcOallocatorlEvectorlEnlocLcLweightlE3gRcOallocatorlEnlocLcLweightlE3gRsPgRsPgRsPgRsPgRcOallocatorlEvectorlEvectorlEnlocLcLweightlE3gRcOallocatorlEnlocLcLweightlE3gRsPgRsPgRcOallocatorlEvectorlEnlocLcLweightlE3gRcOallocatorlEnlocLcLweightlE3gRsPgRsPgRsPgRsPgRsPgRsPgRsPgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum(&G__fastnloDictLN_vectorlEvectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgRcOallocatorlEvectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgRsPgRsPgR);
   G__get_linked_tagnum(&G__fastnloDictLN_reverse_iteratorlEvectorlEvectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgRcOallocatorlEvectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgRsPgRsPgRcLcLiteratorgR);
}
extern "C" void G__cpp_setupfastnloDict(void) {
  G__check_setup_version(30051515,"G__cpp_setupfastnloDict()");
  G__set_cpp_environmentfastnloDict();
  G__cpp_setup_tagtablefastnloDict();

  G__cpp_setup_inheritancefastnloDict();

  G__cpp_setup_typetablefastnloDict();

  G__cpp_setup_memvarfastnloDict();

  G__cpp_setup_memfuncfastnloDict();
  G__cpp_setup_globalfastnloDict();
  G__cpp_setup_funcfastnloDict();

   if(0==G__getsizep2memfunc()) G__get_sizep2memfuncfastnloDict();
  return;
}
class G__cpp_setup_initfastnloDict {
  public:
    G__cpp_setup_initfastnloDict() { G__add_setup_func("fastnloDict",(G__incsetup)(&G__cpp_setupfastnloDict)); G__call_setup_funcs(); }
   ~G__cpp_setup_initfastnloDict() { G__remove_setup_func("fastnloDict"); }
};
G__cpp_setup_initfastnloDict G__cpp_setup_initializerfastnloDict;

