/********************************************************************
* fastnloDict.h
********************************************************************/
#ifdef __CINT__
#error fastnloDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#include "G__ci.h"
extern "C" {
extern void G__cpp_setup_tagtablefastnloDict();
extern void G__cpp_setup_inheritancefastnloDict();
extern void G__cpp_setup_typetablefastnloDict();
extern void G__cpp_setup_memvarfastnloDict();
extern void G__cpp_setup_globalfastnloDict();
extern void G__cpp_setup_memfuncfastnloDict();
extern void G__cpp_setup_funcfastnloDict();
extern void G__set_cpp_environmentfastnloDict();
}


#include "TROOT.h"
#include "TMemberInspector.h"
#include "TIncljets.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__fastnloDictLN_TClass;
extern G__linked_taginfo G__fastnloDictLN_TBuffer;
extern G__linked_taginfo G__fastnloDictLN_TMemberInspector;
extern G__linked_taginfo G__fastnloDictLN_TObject;
extern G__linked_taginfo G__fastnloDictLN_string;
extern G__linked_taginfo G__fastnloDictLN_nlo;
extern G__linked_taginfo G__fastnloDictLN_LHAPDFWrap;
extern G__linked_taginfo G__fastnloDictLN_vectorlEdoublecOallocatorlEdoublegRsPgR;
extern G__linked_taginfo G__fastnloDictLN_reverse_iteratorlEvectorlEdoublecOallocatorlEdoublegRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__fastnloDictLN_TIncljets;
extern G__linked_taginfo G__fastnloDictLN_nlocLcLweightlE3gR;
extern G__linked_taginfo G__fastnloDictLN_vectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgR;
extern G__linked_taginfo G__fastnloDictLN_reverse_iteratorlEvectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__fastnloDictLN_vectorlEnlocLcLweightlE3gRcOallocatorlEnlocLcLweightlE3gRsPgRsPgR;
extern G__linked_taginfo G__fastnloDictLN_reverse_iteratorlEvectorlEnlocLcLweightlE3gRcOallocatorlEnlocLcLweightlE3gRsPgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__fastnloDictLN_vectorlEvectorlEnlocLcLweightlE3gRcOallocatorlEnlocLcLweightlE3gRsPgRsPgRcOallocatorlEvectorlEnlocLcLweightlE3gRcOallocatorlEnlocLcLweightlE3gRsPgRsPgRsPgRsPgR;
extern G__linked_taginfo G__fastnloDictLN_reverse_iteratorlEvectorlEvectorlEnlocLcLweightlE3gRcOallocatorlEnlocLcLweightlE3gRsPgRsPgRcOallocatorlEvectorlEnlocLcLweightlE3gRcOallocatorlEnlocLcLweightlE3gRsPgRsPgRsPgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__fastnloDictLN_vectorlEvectorlEvectorlEnlocLcLweightlE3gRcOallocatorlEnlocLcLweightlE3gRsPgRsPgRcOallocatorlEvectorlEnlocLcLweightlE3gRcOallocatorlEnlocLcLweightlE3gRsPgRsPgRsPgRsPgRcOallocatorlEvectorlEvectorlEnlocLcLweightlE3gRcOallocatorlEnlocLcLweightlE3gRsPgRsPgRcOallocatorlEvectorlEnlocLcLweightlE3gRcOallocatorlEnlocLcLweightlE3gRsPgRsPgRsPgRsPgRsPgRsPgR;
extern G__linked_taginfo G__fastnloDictLN_reverse_iteratorlEvectorlEvectorlEvectorlEnlocLcLweightlE3gRcOallocatorlEnlocLcLweightlE3gRsPgRsPgRcOallocatorlEvectorlEnlocLcLweightlE3gRcOallocatorlEnlocLcLweightlE3gRsPgRsPgRsPgRsPgRcOallocatorlEvectorlEvectorlEnlocLcLweightlE3gRcOallocatorlEnlocLcLweightlE3gRsPgRsPgRcOallocatorlEvectorlEnlocLcLweightlE3gRcOallocatorlEnlocLcLweightlE3gRsPgRsPgRsPgRsPgRsPgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__fastnloDictLN_vectorlEvectorlEvectorlEvectorlEnlocLcLweightlE3gRcOallocatorlEnlocLcLweightlE3gRsPgRsPgRcOallocatorlEvectorlEnlocLcLweightlE3gRcOallocatorlEnlocLcLweightlE3gRsPgRsPgRsPgRsPgRcOallocatorlEvectorlEvectorlEnlocLcLweightlE3gRcOallocatorlEnlocLcLweightlE3gRsPgRsPgRcOallocatorlEvectorlEnlocLcLweightlE3gRcOallocatorlEnlocLcLweightlE3gRsPgRsPgRsPgRsPgRsPgRsPgRcOallocatorlEvectorlEvectorlEvectorlEnlocLcLweightlE3gRcOallocatorlEnlocLcLweightlE3gRsPgRsPgRcOallocatorlEvectorlEnlocLcLweightlE3gRcOallocatorlEnlocLcLweightlE3gRsPgRsPgRsPgRsPgRcOallocatorlEvectorlEvectorlEnlocLcLweightlE3gRcOallocatorlEnlocLcLweightlE3gRsPgRsPgRcOallocatorlEvectorlEnlocLcLweightlE3gRcOallocatorlEnlocLcLweightlE3gRsPgRsPgRsPgRsPgRsPgRsPgRsPgRsPgR;
extern G__linked_taginfo G__fastnloDictLN_reverse_iteratorlEvectorlEvectorlEvectorlEvectorlEnlocLcLweightlE3gRcOallocatorlEnlocLcLweightlE3gRsPgRsPgRcOallocatorlEvectorlEnlocLcLweightlE3gRcOallocatorlEnlocLcLweightlE3gRsPgRsPgRsPgRsPgRcOallocatorlEvectorlEvectorlEnlocLcLweightlE3gRcOallocatorlEnlocLcLweightlE3gRsPgRsPgRcOallocatorlEvectorlEnlocLcLweightlE3gRcOallocatorlEnlocLcLweightlE3gRsPgRsPgRsPgRsPgRsPgRsPgRcOallocatorlEvectorlEvectorlEvectorlEnlocLcLweightlE3gRcOallocatorlEnlocLcLweightlE3gRsPgRsPgRcOallocatorlEvectorlEnlocLcLweightlE3gRcOallocatorlEnlocLcLweightlE3gRsPgRsPgRsPgRsPgRcOallocatorlEvectorlEvectorlEnlocLcLweightlE3gRcOallocatorlEnlocLcLweightlE3gRsPgRsPgRcOallocatorlEvectorlEnlocLcLweightlE3gRcOallocatorlEnlocLcLweightlE3gRsPgRsPgRsPgRsPgRsPgRsPgRsPgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__fastnloDictLN_vectorlEvectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgRcOallocatorlEvectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgRsPgRsPgR;
extern G__linked_taginfo G__fastnloDictLN_reverse_iteratorlEvectorlEvectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgRcOallocatorlEvectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgRsPgRsPgRcLcLiteratorgR;

/* STUB derived class for protected member access */
