TIncljets.o TIncljets.D :  TIncljets.C TIncljets.h \
  /products/ROOT/4.00_06a/gcc-3.3/root/include/TObject.h \
  /products/ROOT/4.00_06a/gcc-3.3/root/include/Rtypes.h \
  /products/ROOT/4.00_06a/gcc-3.3/root/include/RConfig.h \
  /products/ROOT/4.00_06a/gcc-3.3/root/include/RVersion.h \
  /products/ROOT/4.00_06a/gcc-3.3/root/include/DllImport.h \
  /products/ROOT/4.00_06a/gcc-3.3/root/include/Rtypeinfo.h \
  /products/ROOT/4.00_06a/gcc-3.3/root/include/TGenericClassInfo.h \
  /products/ROOT/4.00_06a/gcc-3.3/root/include/Varargs.h \
  /products/ROOT/4.00_06a/gcc-3.3/root/include/TStorage.h \
  /products/ROOT/4.00_06a/gcc-3.3/root/include/Riosfwd.h \
  /products/ROOT/4.00_06a/gcc-3.3/root/include/TBuffer.h \
  /products/ROOT/4.00_06a/gcc-3.3/root/include/Bytes.h \
  /products/ROOT/4.00_06a/gcc-3.3/root/include/Byteswap.h nlo-weight.h \
  LHAPDFWrap.h physconst.h
