fnh2101: fnh2101d.la 
fnh2101d.la: pdf-cteq6.h fnh2101d.cc
	create-nlojet-user fnh2101d.cc -o fnh2101d -Wx,-O0,-Wall,-I${HOME}/include/lhpdf,-I../../common -Wl,-llhpdf_cteq6,-lfastnloAuthor
fnh2101r.la: pdf-cteq6.h fnh2101r.cc
	create-nlojet-user fnh2101r.cc -o fnh2101r -Wx,-O0,-Wall,-I${HOME}/include/lhpdf,-I../../common -Wl,-llhpdf_cteq6,-lfastnloAuthor
